// SPDX-FileCopyrightText: 2025-2026 Volodymyr Papush (21CNCStudio)
// SPDX-License-Identifier: GPL-3.0-or-later
// GPL-3.0-or-later: https://www.gnu.org/licenses/gpl-3.0.html
// Want to use this code in a commercial product while keeping modifications proprietary?
// Purchase a Commercial License: see COMMERCIAL_LICENSE_SUMMARY.md

#include "ui/UiStrings.h"

#include <stddef.h>

namespace UiStrings {

namespace {

constexpr const char *kStringsEn[] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "Index",
    "HCHO",
    "AQI",
    "Initializing",
    "Fresh Air - All Good",
    "Excellent",
    "Good",
    "Moderate",
    "Poor",
    "OFF",
    "ON",
    "OK",
    "ERR",
    "SYNC",
    "Connected",
    "AP Mode",
    "Error",
    "Connecting",
    "Disabled",
    "No WiFi",
    "Connected",
    "Error",
    "Retrying (10m)",
    "Retrying (1h)",
    "Connecting...",
    "ON / OFF",
    "Every 6h",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 Very High! Ventilate now",
    "CO2 High - Ventilate soon",
    "CO2 Rising - Consider ventilation",
    "PM2.5 Very High! Purify - stop smoke",
    "PM2.5 High - Purify - check source",
    "PM2.5 Elevated - Consider purifier",
    "PM10 Very High! Purify - check source",
    "PM10 High - Purify - reduce dust",
    "PM10 Elevated - Purify - reduce dust",
    "HCHO Very High! Ventilate - remove source",
    "HCHO High - Ventilate - remove source",
    "HCHO Detected - Check sources",
    "VOC Very High! Find source - vent",
    "VOC High - Increase ventilation",
    "NOx Very High! Stop source - ventilate",
    "NOx High - Use hood - check source",
    "NOx Elevated - Check stove/outside",
    "Temp Too Cold! Heat now",
    "Temp Cold - Heat the room",
    "Temp Slightly Cool - Add heat",
    "Temp Too Hot! Cool now",
    "Temp Warm - Ventilate / cool",
    "Temp Slightly Warm - Increase airflow",
    "DP Very Low! Humidify",
    "DP Low - Air may feel dry",
    "DP Muggy! Dehumidify now",
    "DP Very High - Vent/dehumidify",
    "DP High - Air may feel muggy",
    "Humidity Extremely Low! Humidify",
    "Humidity Very Low - Use humidifier",
    "Humidity Low - Consider humidifier",
    "Humidity Extremely High! Dehumidify",
    "Humidity Very High - Dehumidify",
    "Humidity High - Increase airflow",
    "SETTINGS",
    "SETTINGS",
    "SAVE & BACK",
    "TEMP OFFSET",
    "HUMID OFFSET",
    "NIGHT MODE",
    "C / F",
    "HEAD STATUS",
    "WI-FI",
    "TIME / DATE",
    "THEME COLOR",
    "MQTT",
    "AUTO NIGHT",
    "RESTART",
    "FACTORY\nRESET",
    "CO2\nCALLIBRATION",
    "ABOUT",
    "DOT\nINDICATORS",
    "ALERT\nBLINK",
    "VOC\nRELEARN",
    "BACKLIGHT",
    "WI-FI SETTINGS",
    "Wi-Fi status:",
    "To configure Wi-Fi:\n- Press ON / OFF button\n- Connect your phone or PC to network \"ProjectAura-Setup\".\n- Open http://192.168.4.1 in browser or scan QR code.\n- Select your home Wi-Fi network and enter the password.\n",
    "SSID:",
    "IP:",
    "FORGET\nWI-FI",
    "RECONNECT",
    "START AP",
    "MQTT SETTINGS",
    "MQTT status:",
    "To configure MQTT:\n- Connect Project Aura to WI-FI first\n- Open http://aura.local/mqtt in browser or scan QR code.",
    "Device IP:",
    "Broker IP:",
    "Topic:",
    "RECONNECT",
    "DATE & TIME",
    "TIME ZONE",
    "AUTO SYNC (NTP)",
    "SET TIME",
    "Hours:",
    "Minutes:",
    "SET DATE",
    "Day:",
    "Month:",
    "Year:",
    "TIME",
    "APPLY NOW",
    "PCF8523:",
    "WIFI:",
    "NTP:",
    "STATUS: ",
    "TEMPERATURE",
    "HUMIDITY",
    "PRESSURE",
    "WARMUP",
    "RESET VOC",
    "RESTART",
    "RESET",
    "CANCEL",
    "Reset VOC Calibration?",
    "VOC/NOx learning will restart.\nReadings may be unstable for a few hours.",
    "Restart Device?",
    "The device will reboot.\nReadings will pause briefly.",
    "Factory Reset?",
    "This clears Wi-Fi, offsets, themes,\nschedules and VOC state.\nThis cannot be undone.",
    "THEME:",
    "CUSTOM",
    "PRESETS",
    "EXAMPLE:",
    "To configure custom theme:\n- Connect Project Aura to WI-FI first\n- Open http://aura.local/theme in browser \nor scan QR code.\n- Save by pressing Back",
    "AUTO NIGHT MODE",
    "This feature activates \"Night Mode\" colors based on a schedule.\n- Set Start and End times below.\n- Toggle the switch to ON.\n- Manual Night Mode is disabled when Auto Night is ON.",
    "START TIME",
    "END TIME",
    "SCREEN BACKLIGHT",
    "Device monitors air quality while screen is off.\nSensors remain active. Touch to wake.",
    "SCHEDULED SLEEP",
    "POWER SAVING",
    "SLEEP AT",
    "WAKE AT",
    "ALWAYS ON",
    "30 SEC",
    "1 MIN",
    "5 MIN",
    "CO2 Calibration (Fresh Air)",
    "CALIBRATE CO2",
    "- ASC (Automatic Self-Calibration): ON by default.\n- Best when CO2 drops close to outdoor levels at least weekly\n(good ventilation / room unoccupied).\n- ASC adjusts slowly over days (not instantly).\n- With ASC ON, manual calibration is usually \nnot needed.",
    "- Power the device from a power bank.\n- Take it outdoors to clean fresh air.\n- Keep it away from people (breath), windows, cars, smoke, vents.\n- Let it run for 10 minutes (minimum 5).\n- Press Calibrate CO2 and keep the device still.\n- Manual calibration is for troubleshooting only.\n- Do not calibrate more than once every 6 months.\n- Calibration uses a 420 ppm reference.\n- Wrong conditions can make readings worse.",
    "TAP TO CONTINUE",
    "BOOT DIAGNOSTICS",
    "System",
    "Sensors",
    "App:",
    "MAC:",
    "Reset:",
    "Heap:",
    "Storage:",
    "I2C:",
    "Touch:",
    "SEN66:",
    "SFA30:",
    "PCF8523:",
    "Errors detected",
    "OK (config)",
    "OK (defaults)",
    "RECOVERED",
    "DETECTED",
    "FAIL",
    "STARTING",
    "NOT FOUND",
    "LOST"
};

constexpr const char *kStringsDe[] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "Index",
    "HCHO",
    "AQI",
    "Initialisiere...",
    "Frische Luft - Alles gut",
    "Ausgezeichnet",
    "Gut",
    "Mittel",
    "Schlecht",
    "AUS",
    "AN",
    "OK",
    "ERR",
    "SYNC",
    "Verbunden",
    "AP Modus",
    "Fehler",
    "Verbinde...",
    "Deaktiviert",
    "Kein WLAN",
    "Verbunden",
    "Fehler",
    "Wiederholen (10m)",
    "Wiederholen (1h)",
    "Verbinde...",
    "AN / AUS",
    "Alle 6h",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 Sehr hoch! Jetzt lüften",
    "CO2 Hoch - Bald lüften",
    "CO2 Steigt - Lüften erwägen",
    "PM2.5 Sehr hoch! Reinigen - Rauch stoppen",
    "PM2.5 Hoch - Reinigen - Quelle prüfen",
    "PM2.5 Erhöht - Reiniger erwägen",
    "PM10 Sehr hoch! Reinigen - Quelle prüfen",
    "PM10 Hoch - Reinigen - Staub reduzieren",
    "PM10 Erhöht - Staub reduzieren",
    "HCHO Sehr hoch! Lüften - Quelle weg",
    "HCHO Hoch - Lüften - Quelle weg",
    "HCHO Erkannt - Quellen prüfen",
    "VOC Sehr hoch! Quelle finden - lüften",
    "VOC Hoch - Mehr lüften",
    "NOx Sehr hoch! Quelle stoppen - lüften",
    "NOx Hoch - Abzug nutzen - Quelle prüfen",
    "NOx Erhöht - Herd/Außen prüfen",
    "Zu kalt! Heizen",
    "Kalt - Raum heizen",
    "Etwas kühl - Mehr Wärme",
    "Zu heiß! Kühlen",
    "Warm - Lüften / kühlen",
    "Etwas warm - Mehr Luft",
    "DP Sehr niedrig! Befeuchten",
    "DP Niedrig - Luft kann trocken sein",
    "DP Schwül! Entfeuchten",
    "DP Sehr hoch - Lüften/entfeuchten",
    "DP Hoch - Luft kann schwül sein",
    "Luftfeuchte Extrem niedrig! Befeuchten",
    "Luftfeuchte Sehr niedrig - Befeuchter",
    "Luftfeuchte Niedrig - Befeuchter erwägen",
    "Luftfeuchte Extrem hoch! Entfeuchten",
    "Luftfeuchte Sehr hoch - Entfeuchten",
    "Luftfeuchte Hoch - Mehr Luft",
    "EINSTELL",
    "EINSTELL",
    "ZURÜCK",
    "TEMP-KORR.",
    "FEUCHT-KORR.",
    "NACHTMODUS",
    "C / F",
    "HEAD STATUS",
    "WI-FI",
    "ZEIT / DATUM",
    "THEME FARBE",
    "MQTT",
    "AUTO NACHT",
    "NEUSTART",
    "WERKS\nRESET",
    "CO2\nKALIBR.",
    "INFO",
    "PUNKT\nANZEIGE",
    "ALARM\nBLINK",
    "VOC\nNEU LERN.",
    "HINTERLICHT",
    "WLAN EINSTELLUNGEN",
    "WLAN Status:",
    "WLAN einrichten:\n- ON / OFF drücken\n- Mit \"ProjectAura-Setup\" verbinden\n- http://192.168.4.1 öffnen oder QR-Code scannen\n- Heimnetz wählen und Passwort eingeben\n",
    "SSID:",
    "IP:",
    "WLAN\nLÖSCHEN",
    "VERBINDEN",
    "AP START",
    "MQTT EINSTELLUNGEN",
    "MQTT Status:",
    "MQTT einrichten:\n- Project Aura zuerst mit WLAN verbinden\n- http://aura.local/mqtt öffnen oder QR-Code scannen",
    "Gerät IP:",
    "Broker IP:",
    "Topic:",
    "VERBINDEN",
    "DATUM & ZEIT",
    "ZEITZONE",
    "AUTO SYNC (NTP)",
    "ZEIT SETZEN",
    "Stunden:",
    "Minuten:",
    "DATUM SETZEN",
    "Tag:",
    "Monat:",
    "Jahr:",
    "ZEIT",
    "JETZT ANWENDEN",
    "PCF8523:",
    "WLAN:",
    "NTP:",
    "STATUS: ",
    "TEMPERATUR",
    "LUFTFEUCHTE",
    "DRUCK",
    "WARMLAUF",
    "VOC RESET",
    "NEUSTART",
    "RESET",
    "ABBRECHEN",
    "VOC-Kalibrierung zurücksetzen?",
    "VOC/NOx-Lernen wird neu gestartet.\nWerte können einige Stunden instabil sein.",
    "Gerät neu starten?",
    "Das Gerät wird neu gestartet.\nMesswerte pausieren kurz.",
    "Werkseinstellungen zurücksetzen?",
    "Dies löscht WLAN, Offsets, Themes,\nZeitpläne und VOC-Status.\nDies kann nicht rückgängig gemacht werden.",
    "THEME:",
    "EIGEN",
    "VORLAGEN",
    "BEISPIEL:",
    "Custom-Theme einrichten:\n- Project Aura zuerst mit WLAN verbinden\n- http://aura.local/theme öffnen oder QR-Code scannen\n- Mit Zurück speichern",
    "AUTO NACHTMODUS",
    "Diese Funktion aktiviert \"Nachtmodus\" nach Zeitplan.\n- Start- und Endzeit einstellen.\n- Schalter auf AN.\n- Manueller Nachtmodus ist deaktiviert,\n  wenn Auto Nacht aktiv ist.",
    "STARTZEIT",
    "ENDZEIT",
    "HINTERLICHT",
    "Gerät überwacht Luftqualität bei ausgeschaltetem Bildschirm.\nSensoren bleiben aktiv. Berühren zum Aufwecken.",
    "GEPLANTER SCHLAF",
    "ENERGIESPAREN",
    "SCHLAFEN UM",
    "AUFWACHEN UM",
    "IMMER AN",
    "30 SEK",
    "1 MIN",
    "5 MIN",
    "CO2 Kalibrierung (Frischluft)",
    "CO2 KALIBRIEREN",
    "- ASC (Auto-Selbstkalibrierung): Standardmäßig AN.\n- Am besten, wenn CO2 mind. wöchentlich nahe Außenluft fällt\n  (gute Lüftung / Raum unbesetzt).\n- ASC passt sich langsam über Tage an (nicht sofort).\n- Mit ASC AN ist manuelle Kalibrierung meist nicht nötig.",
    "- Gerät mit Powerbank betreiben.\n- Nach draußen an frische Luft bringen.\n- Fern von Menschen (Atem), Fenstern, Autos, Rauch, Lüftungen.\n- 10 Minuten laufen lassen (mind. 5).\n- CO2 kalibrieren drücken und Gerät ruhig halten.\n- Manuelle Kalibrierung nur zur Fehlersuche.\n- Nicht öfter als alle 6 Monate kalibrieren.\n- Kalibrierung nutzt 420 ppm Referenz.\n- Falsche Bedingungen verschlechtern die Messung.",
    "TIPPE ZUM FORTFAHREN",
    "BOOT-DIAGNOSE",
    "System",
    "Sensoren",
    "App:",
    "MAC:",
    "Reset:",
    "Heap:",
    "Speicher:",
    "I2C:",
    "Touch:",
    "SEN66:",
    "SFA30:",
    "PCF8523:",
    "Fehler erkannt",
    "OK (Konfig)",
    "OK (Standard)",
    "WIEDER OK",
    "ERKANNT",
    "FEHLER",
    "STARTET...",
    "NICHT GEFUNDEN",
    "VERLOREN"
};

static_assert(sizeof(kStringsDe) / sizeof(kStringsDe[0]) ==
              static_cast<size_t>(TextId::Count),
              "UiStrings: DE table size mismatch");

constexpr const char *kStringsFr[static_cast<size_t>(TextId::Count)] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "Index",
    "HCHO",
    "AQI",
    "Initialisation",
    "Air frais - Tout va bien",
    "Excellent",
    "Bon",
    "Moyen",
    "Mauvais",
    "OFF",
    "ON",
    "OK",
    "ERR",
    "SYNC",
    "Connecté",
    "Mode AP",
    "Erreur",
    "Connexion",
    "Désactivé",
    "Pas de Wi-Fi",
    "Connecté",
    "Erreur",
    "Nouvel essai (10m)",
    "Nouvel essai (1h)",
    "Connexion...",
    "ON / OFF",
    "Toutes les 6h",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 très élevé! Aérez maintenant",
    "CO2 élevé - Aérez bientôt",
    "CO2 en hausse - Pensez à aérer",
    "PM2.5 très élevé! Purifiez - stop fumée",
    "PM2.5 élevé - Purifiez - source?",
    "PM2.5 élevé - Pensez purificateur",
    "PM10 très élevé! Purifiez - source?",
    "PM10 élevé - Purifiez - réduisez poussière",
    "PM10 modéré - Réduisez poussière",
    "HCHO très élevé! Aérez - supprimez source",
    "HCHO élevé - Aérez - supprimez source",
    "HCHO détecté - Vérifiez sources",
    "VOC très élevé! Trouvez source - aérez",
    "VOC élevé - Augmentez ventilation",
    "NOx très élevé! Stop source - aérez",
    "NOx élevé - Utilisez hotte - source",
    "NOx modéré - Vérifiez cuisine/dehors",
    "Temp trop basse! Chauffez",
    "Temp basse - Chauffez la pièce",
    "Temp un peu basse - Plus de chaleur",
    "Temp trop haute! Refroidissez",
    "Temp chaude - Aérez / refroidissez",
    "Temp un peu chaude - Plus d'air",
    "DP très bas! Humidifiez",
    "DP bas - Air peut sembler sec",
    "DP lourd! Déshumidifiez",
    "DP très haut - Aérez/déshumidifiez",
    "DP haut - Air peut sembler lourd",
    "Humidité très basse! Humidifiez",
    "Humidité très basse - Humidificateur",
    "Humidité basse - Pensez humidifier",
    "Humidité très élevée! Déshumidifiez",
    "Humidité très élevée - Déshumidifiez",
    "Humidité élevée - Plus d'air",
    "RÉGLAGES",
    "RÉGLAGES",
    "RETOUR",
    "CORR. TEMP",
    "CORR. HUM",
    "MODE NUIT",
    "C / F",
    "ÉTAT HEAD",
    "WI-FI",
    "HEURE / DATE",
    "COULEUR THÈME",
    "MQTT",
    "AUTO NUIT",
    "REDÉMARRER",
    "RESET\nUSINE",
    "CO2\nCALIBR.",
    "INFO",
    "POINTS\nLED",
    "ALERTE\nCLIGN.",
    "VOC\nRÉAPPR.",
    "ÉCLAIRAGE",
    "RÉGLAGES WI-FI",
    "Statut Wi-Fi:",
    "Pour configurer le Wi-Fi:\n- Appuyez sur ON / OFF\n- Connectez votre téléphone ou PC à \"ProjectAura-Setup\".\n- Ouvrez http://192.168.4.1 ou scannez le QR.\n- Choisissez votre réseau Wi-Fi et entrez le mot de passe.\n",
    "SSID:",
    "IP:",
    "OUBLIER\nWI-FI",
    "RECONNECTER",
    "DÉMARRER AP",
    "RÉGLAGES MQTT",
    "Statut MQTT:",
    "Pour configurer MQTT:\n- Connectez Project Aura au WI-FI d'abord\n- Ouvrez http://aura.local/mqtt ou scannez le QR.",
    "IP appareil:",
    "IP broker:",
    "Topic:",
    "RECONNECTER",
    "DATE & HEURE",
    "FUSEAU HORAIRE",
    "SYNC AUTO (NTP)",
    "RÉGLER HEURE",
    "Heures:",
    "Minutes:",
    "RÉGLER DATE",
    "Jour:",
    "Mois:",
    "Année:",
    "HEURE",
    "APPLIQUER",
    "PCF8523:",
    "WIFI:",
    "NTP:",
    "ÉTAT: ",
    "TEMPÉRATURE",
    "HUMIDITÉ",
    "PRESSION",
    "CHAUFFE",
    "RESET VOC",
    "REDÉMARRER",
    "RESET",
    "ANNULER",
    "Réinitialiser VOC?",
    "L'apprentissage VOC/NOx redémarre.\nMesures instables quelques heures.",
    "Redémarrer l'appareil?",
    "L'appareil va redémarrer.\nMesures en pause brièvement.",
    "Réinit. usine?",
    "Efface Wi-Fi, offsets, thèmes,\nplannings et état VOC.\nAction irréversible.",
    "THÈME:",
    "PERSO",
    "PRÉSETS",
    "EXEMPLE:",
    "Pour thème personnalisé:\n- Connectez Project Aura au WI-FI d'abord\n- Ouvrez http://aura.local/theme\n  ou scannez le QR.\n- Enregistrer via Retour",
    "MODE NUIT AUTO",
    "Active les couleurs \"Mode Nuit\" par horaire.\n- Réglez début et fin.\n- Mettez l'interrupteur sur ON.\n- Mode Nuit manuel désactivé\n  quand Auto Nuit est ON.",
    "HEURE DÉBUT",
    "HEURE FIN",
    "ÉCLAIRAGE ÉCRAN",
    "Mesure l'air écran éteint.\nCapteurs actifs. Touchez pour réveiller.",
    "SOMMEIL PROGRAMMÉ",
    "ÉCONOMIE ÉNERGIE",
    "DORMIR À",
    "RÉVEIL À",
    "TOUJOURS",
    "30 SEC",
    "1 MIN",
    "5 MIN",
    "Calibrage CO2 (Air frais)",
    "CALIBRER CO2",
    "- ASC (Auto Self-Calibration): ON par défaut.\n- Idéal si CO2 baisse proche extérieur chaque semaine\n  (bonne ventilation / pièce vide).\n- ASC ajuste lentement (jours, pas instantané).\n- Avec ASC ON, calibration manuelle\n  généralement inutile.",
    "- Alimentez avec power bank.\n- Sortez à l'air frais.\n- Éloignez de personnes, fenêtres, voitures, fumée, sorties.\n- Laissez 10 min (min 5).\n- Appuyez Calibrer CO2 et ne bougez pas.\n- Calibration manuelle pour dépannage.\n- Pas plus d'une fois / 6 mois.\n- Référence 420 ppm.\n- Mauvaises conditions dégradent les mesures.",
    "TOUCHEZ POUR CONTINUER",
    "DIAGNOSTIC BOOT",
    "Système",
    "Capteurs",
    "App:",
    "MAC:",
    "Reset:",
    "Heap:",
    "Stockage:",
    "I2C:",
    "Touch:",
    "SEN66:",
    "SFA30:",
    "PCF8523:",
    "Erreurs détectées",
    "OK (config)",
    "OK (défaut)",
    "RÉTABLI",
    "DÉTECTÉ",
    "ÉCHEC",
    "DÉMARRAGE",
    "NON TROUVÉ",
    "PERDU"
};

static_assert(sizeof(kStringsFr) / sizeof(kStringsFr[0]) ==
              static_cast<size_t>(TextId::Count),
              "UiStrings: FR table size mismatch");

constexpr const char *kStringsIt[static_cast<size_t>(TextId::Count)] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "Index",
    "HCHO",
    "AQI",
    "Inizializzazione",
    "Aria fresca - Tutto ok",
    "Eccellente",
    "Buono",
    "Moderato",
    "Scarso",
    "OFF",
    "ON",
    "OK",
    "ERR",
    "SYNC",
    "Connesso",
    "Modalità AP",
    "Errore",
    "Connessione",
    "Disattivato",
    "No Wi-Fi",
    "Connesso",
    "Errore",
    "Riprova (10m)",
    "Riprova (1h)",
    "Connessione...",
    "ON / OFF",
    "Ogni 6h",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 molto alto! Arieggia ora",
    "CO2 alto - Arieggia presto",
    "CO2 in aumento - Considera ventilazione",
    "PM2.5 molto alto! Purifica - stop fumo",
    "PM2.5 alto - Purifica - controlla fonte",
    "PM2.5 elevato - Valuta purificatore",
    "PM10 molto alto! Purifica - controlla fonte",
    "PM10 alto - Purifica - riduci polvere",
    "PM10 elevato - Purifica - riduci polvere",
    "HCHO molto alto! Arieggia - rimuovi fonte",
    "HCHO alto - Arieggia - rimuovi fonte",
    "HCHO rilevato - Controlla fonti",
    "VOC molto alto! Trova fonte - arieggia",
    "VOC alto - Aumenta ventilazione",
    "NOx molto alto! Ferma fonte - arieggia",
    "NOx alto - Usa cappa - controlla fonte",
    "NOx elevato - Controlla cucina/esterno",
    "Temp troppo bassa! Riscalda",
    "Temp bassa - Riscalda la stanza",
    "Temp un po' bassa - Più calore",
    "Temp troppo alta! Raffredda",
    "Temp alta - Arieggia / raffredda",
    "Temp un po' alta - Più aria",
    "DP molto basso! Umidifica",
    "DP basso - Aria può sembrare secca",
    "DP afoso! Deumidifica",
    "DP molto alto - Arieggia/deumidifica",
    "DP alto - Aria può essere afosa",
    "Umidità molto bassa! Umidifica",
    "Umidità molto bassa - Usa umidificatore",
    "Umidità bassa - Valuta umidificatore",
    "Umidità molto alta! Deumidifica",
    "Umidità molto alta - Deumidifica",
    "Umidità alta - Più ventilazione",
    "IMPOSTAZIONI",
    "IMPOST",
    "INDIETRO",
    "OFFSET TEMP",
    "OFFSET UMID",
    "MODO NOTTE",
    "C / F",
    "STATO HEAD",
    "WI-FI",
    "ORA / DATA",
    "COLORE TEMA",
    "MQTT",
    "AUTO NOTTE",
    "RIAVVIA",
    "RESET\nFABBRICA",
    "CO2\nCALIBR.",
    "INFO",
    "PUNTI\nINDIC.",
    "ALLARME\nLAMP.",
    "VOC\nRIAPP.",
    "RETROILL.",
    "IMPOSTAZIONI WI-FI",
    "Stato Wi-Fi:",
    "Per configurare il Wi-Fi:\n- Premi ON / OFF\n- Connetti telefono o PC a \"ProjectAura-Setup\".\n- Apri http://192.168.4.1 o scansiona QR.\n- Seleziona la rete Wi-Fi e inserisci la password.\n",
    "SSID:",
    "IP:",
    "DIMENTICA\nWI-FI",
    "RICOLLEGA",
    "AVVIA AP",
    "IMPOSTAZIONI MQTT",
    "Stato MQTT:",
    "Per configurare MQTT:\n- Connetti Project Aura al WI-FI prima\n- Apri http://aura.local/mqtt o scansiona QR.",
    "IP dispositivo:",
    "IP broker:",
    "Topic:",
    "RICOLLEGA",
    "DATA E ORA",
    "FUSO ORARIO",
    "SYNC AUTO (NTP)",
    "IMPOSTA ORA",
    "Ore:",
    "Minuti:",
    "IMPOSTA DATA",
    "Giorno:",
    "Mese:",
    "Anno:",
    "ORA",
    "APPLICA",
    "PCF8523:",
    "WIFI:",
    "NTP:",
    "STATO: ",
    "TEMPERATURA",
    "UMIDITÀ",
    "PRESSIONE",
    "RISCALD.",
    "RESET VOC",
    "RIAVVIA",
    "RESET",
    "ANNULLA",
    "Reset calibrazione VOC?",
    "L'apprendimento VOC/NOx riparte.\nLetture instabili per alcune ore.",
    "Riavvia dispositivo?",
    "Il dispositivo si riavvia.\nLetture in pausa brevemente.",
    "Reset di fabbrica?",
    "Cancella Wi-Fi, offset, temi,\nprogrammi e stato VOC.\nAzione irreversibile.",
    "TEMA:",
    "PERSON.",
    "PRESET",
    "ESEMPIO:",
    "Per tema personalizzato:\n- Connetti Project Aura al WI-FI prima\n- Apri http://aura.local/theme\n  o scansiona QR.\n- Salva con Indietro",
    "MODO NOTTE AUTO",
    "Attiva colori \"Modo Notte\" a orario.\n- Imposta inizio e fine.\n- Interruttore su ON.\n- Modo Notte manuale disattivato\n  quando Auto Notte è ON.",
    "ORA INIZIO",
    "ORA FINE",
    "RETROILLUMINAZ.",
    "Misura aria a schermo spento.\nSensori attivi. Tocca per svegliare.",
    "SONNO PROGRAM.",
    "RISPARMIO",
    "DORMI ALLE",
    "SVEGLIA ALLE",
    "SEMPRE",
    "30 SEC",
    "1 MIN",
    "5 MIN",
    "Calibrazione CO2 (Aria fresca)",
    "CALIBRA CO2",
    "- ASC (Auto Self-Calibration): ON per default.\n- Ideale se CO2 scende vicino esterno ogni settimana\n  (buona ventilazione / stanza vuota).\n- ASC regola lentamente (giorni, non istantaneo).\n- Con ASC ON, calibrazione manuale\n  di solito non necessaria.",
    "- Alimenta con power bank.\n- Porta all'aperto in aria pulita.\n- Lontano da persone, finestre, auto, fumo, bocchette.\n- Lascia 10 min (min 5).\n- Premi Calibra CO2 e non muovere.\n- Calibrazione manuale solo diagnostica.\n- Non più di una volta / 6 mesi.\n- Riferimento 420 ppm.\n- Condizioni errate peggiorano letture.",
    "TOCCA PER CONTINUARE",
    "DIAGNOSTICA BOOT",
    "Sistema",
    "Sensori",
    "App:",
    "MAC:",
    "Reset:",
    "Heap:",
    "Memoria:",
    "I2C:",
    "Touch:",
    "SEN66:",
    "SFA30:",
    "PCF8523:",
    "Errori rilevati",
    "OK (config)",
    "OK (default)",
    "RECUPERATO",
    "RILEVATO",
    "FALLITO",
    "AVVIO",
    "NON TROVATO",
    "PERSO"
};

static_assert(sizeof(kStringsIt) / sizeof(kStringsIt[0]) ==
              static_cast<size_t>(TextId::Count),
              "UiStrings: IT table size mismatch");

constexpr const char *kStringsEs[static_cast<size_t>(TextId::Count)] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "Index",
    "HCHO",
    "AQI",
    "Inicializando",
    "Aire fresco - Todo bien",
    "Excelente",
    "Bueno",
    "Moderado",
    "Malo",
    "OFF",
    "ON",
    "OK",
    "ERR",
    "SYNC",
    "Conectado",
    "Modo AP",
    "Error",
    "Conectando",
    "Desactivado",
    "Sin WiFi",
    "Conectado",
    "Error",
    "Reintento (10m)",
    "Reintento (1h)",
    "Conectando...",
    "ON / OFF",
    "Cada 6h",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 muy alto! Ventila ahora",
    "CO2 alto - Ventila pronto",
    "CO2 subiendo - Considera ventilar",
    "PM2.5 muy alto! Purifica - detén humo",
    "PM2.5 alto - Purifica - revisa origen",
    "PM2.5 elevado - Considera purificador",
    "PM10 muy alto! Purifica - revisa origen",
    "PM10 alto - Purifica - reduce polvo",
    "PM10 elevado - Purifica - reduce polvo",
    "HCHO muy alto! Ventila - elimina fuente",
    "HCHO alto - Ventila - elimina fuente",
    "HCHO detectado - Revisa fuentes",
    "VOC muy alto! Busca fuente - ventila",
    "VOC alto - Aumenta ventilación",
    "NOx muy alto! Detén fuente - ventila",
    "NOx alto - Usa extractor - revisa origen",
    "NOx elevado - Revisa cocina/exterior",
    "Temp muy baja! Calienta ahora",
    "Temp baja - Calienta la sala",
    "Temp algo baja - Más calor",
    "Temp muy alta! Enfría ahora",
    "Temp alta - Ventila / enfría",
    "Temp algo alta - Más aire",
    "DP muy bajo! Humidifica",
    "DP bajo - Aire puede sentirse seco",
    "DP bochornoso! Deshumidifica",
    "DP muy alto - Ventila/deshumidifica",
    "DP alto - Aire puede sentirse bochornoso",
    "Humedad extremadamente baja! Humidifica",
    "Humedad muy baja - Usa humidificador",
    "Humedad baja - Considera humidificador",
    "Humedad extremadamente alta! Deshumidifica",
    "Humedad muy alta - Deshumidifica",
    "Humedad alta - Aumenta ventilación",
    "AJUSTES",
    "AJUSTES",
    "ATRÁS",
    "CORR. TEMP",
    "CORR. HUM",
    "MODO NOCHE",
    "C / F",
    "ESTADO HEAD",
    "WI-FI",
    "HORA / FECHA",
    "COLOR TEMA",
    "MQTT",
    "AUTO NOCHE",
    "REINICIAR",
    "RESET\nFÁBRICA",
    "CO2\nCALIBR.",
    "INFO",
    "PUNTOS\nINDIC.",
    "ALERTA\nPARP.",
    "VOC\nREAPREND.",
    "RETROILUM",
    "AJUSTES WI-FI",
    "Estado Wi-Fi:",
    "Para configurar Wi-Fi:\n- Pulsa ON / OFF\n- Conecta tu móvil o PC a \"ProjectAura-Setup\".\n- Abre http://192.168.4.1 o escanea el QR.\n- Elige tu red Wi-Fi y escribe la clave.\n",
    "SSID:",
    "IP:",
    "OLVIDAR\nWI-FI",
    "RECONECTAR",
    "INICIAR AP",
    "AJUSTES MQTT",
    "Estado MQTT:",
    "Para configurar MQTT:\n- Conecta Project Aura a WI-FI primero\n- Abre http://aura.local/mqtt o escanea el QR.",
    "IP dispositivo:",
    "IP broker:",
    "Topic:",
    "RECONECTAR",
    "FECHA Y HORA",
    "ZONA HORARIA",
    "AUTO SINCR. (NTP)",
    "AJUSTAR HORA",
    "Horas:",
    "Minutos:",
    "AJUSTAR FECHA",
    "Día:",
    "Mes:",
    "Año:",
    "HORA",
    "APLICAR",
    "PCF8523:",
    "WIFI:",
    "NTP:",
    "ESTADO: ",
    "TEMPERATURA",
    "HUMEDAD",
    "PRESIÓN",
    "CALENTANDO",
    "RESET VOC",
    "REINICIAR",
    "RESET",
    "CANCELAR",
    "¿Reiniciar calibración VOC?",
    "El aprendizaje VOC/NOx se reiniciará.\nLas lecturas pueden ser inestables unas horas.",
    "¿Reiniciar dispositivo?",
    "El dispositivo se reiniciará.\nLas lecturas se pausarán brevemente.",
    "¿Restablecer de fábrica?",
    "Esto borra Wi-Fi, offsets, temas,\nhorarios y estado VOC.\nNo se puede deshacer.",
    "TEMA:",
    "PERSONAL",
    "PRESETS",
    "EJEMPLO:",
    "Para tema personalizado:\n- Conecta Project Aura a WI-FI primero\n- Abre http://aura.local/theme \n  o escanea el QR.\n- Guarda pulsando Atrás",
    "MODO NOCHE AUTO",
    "Esta función activa \"Modo Noche\" por horario.\n- Ajusta hora inicio y fin.\n- Pon el interruptor en ON.\n- Modo Noche manual se desactiva\n  cuando Auto Noche está ON.",
    "HORA INICIO",
    "HORA FIN",
    "LUZ DE PANTALLA",
    "El dispositivo mide aire con pantalla apagada.\nSensores siguen activos. Toca para despertar.",
    "SUEÑO PROGRAMADO",
    "AHORRO ENERGÍA",
    "DORMIR A",
    "DESPERTAR A",
    "SIEMPRE",
    "30 SEG",
    "1 MIN",
    "5 MIN",
    "Calibración CO2 (Aire fresco)",
    "CALIBRAR CO2",
    "- ASC (Auto Self-Calibration): ON por defecto.\n- Mejor si CO2 baja cerca de exterior cada semana\n  (buena ventilación / sala vacía).\n- ASC ajusta lento (días, no al instante).\n- Con ASC ON normalmente no hace falta\n  calibración manual.",
    "- Alimenta con power bank.\n- Llévalo afuera a aire limpio.\n- Lejos de personas, ventanas, coches, humo, salidas.\n- Déjalo 10 min (mín. 5).\n- Pulsa Calibrar CO2 y no lo muevas.\n- Calibración manual solo para diagnóstico.\n- No más de cada 6 meses.\n- Usa referencia 420 ppm.\n- Malas condiciones empeoran lecturas.",
    "TOCA PARA SEGUIR",
    "DIAGNÓSTICO BOOT",
    "Sistema",
    "Sensores",
    "App:",
    "MAC:",
    "Reset:",
    "Heap:",
    "Almacenamiento:",
    "I2C:",
    "Touch:",
    "SEN66:",
    "SFA30:",
    "PCF8523:",
    "Errores detectados",
    "OK (config)",
    "OK (defecto)",
    "RECUPERADO",
    "DETECTADO",
    "FALLO",
    "INICIANDO",
    "NO ENCONTRADO",
    "PERDIDO"
};

static_assert(sizeof(kStringsEn) / sizeof(kStringsEn[0]) ==
              static_cast<size_t>(TextId::Count),
              "UiStrings: EN table size mismatch");

Language g_language = Language::EN;

const char *const *tableFor(Language lang) {
    switch (lang) {
        case Language::DE: return kStringsDe;
        case Language::ES: return kStringsEs;
        case Language::FR: return kStringsFr;
        case Language::IT: return kStringsIt;
        case Language::EN:
        default:
            return kStringsEn;
    }
}

} // namespace

void setLanguage(Language lang) {
    g_language = lang;
}

Language language() {
    return g_language;
}

const char *text(TextId id) {
    const size_t index = static_cast<size_t>(id);
    const char *const *table = tableFor(g_language);
    const char *value = table ? table[index] : nullptr;
    if (!value || !*value) {
        value = kStringsEn[index];
    }
    return value ? value : "";
}

} // namespace UiStrings
