// SPDX-FileCopyrightText: 2025-2026 Volodymyr Papush (21CNCStudio)
// SPDX-License-Identifier: GPL-3.0-or-later
// GPL-3.0-or-later: https://www.gnu.org/licenses/gpl-3.0.html
// Want to use this code in a commercial product while keeping modifications proprietary?
// Purchase a Commercial License: see COMMERCIAL_LICENSE_SUMMARY.md

#include "ui/UiStrings.h"

#include <stddef.h>

namespace UiStrings {

namespace {

constexpr const char *kStringsEn[] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "Index",
    "HCHO",
    "AQI",
    "Initializing",
    "Fresh Air - All Good",
    "Excellent",
    "Good",
    "Moderate",
    "Poor",
    "OFF",
    "ON",
    "OK",
    "ERR",
    "SYNC",
    "Connected",
    "AP Mode",
    "Error",
    "Connecting",
    "Disabled",
    "No WiFi",
    "Connected",
    "Error",
    "Retrying (10m)",
    "Retrying (1h)",
    "Connecting...",
    "ON / OFF",
    "Every 6h",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 Very High! Ventilate now",
    "CO2 High - Ventilate soon",
    "CO2 Rising - Consider ventilation",
    "PM2.5 Very High! Purify - stop smoke",
    "PM2.5 High - Purify - check source",
    "PM2.5 Elevated - Consider purifier",
    "PM10 Very High! Purify - check source",
    "PM10 High - Purify - reduce dust",
    "PM10 Elevated - Purify - reduce dust",
    "HCHO Very High! Ventilate - remove source",
    "HCHO High - Ventilate - remove source",
    "HCHO Detected - Check sources",
    "VOC Very High! Find source - vent",
    "VOC High - Increase ventilation",
    "NOx Very High! Stop source - ventilate",
    "NOx High - Use hood - check source",
    "NOx Elevated - Check stove/outside",
    "Temp Too Cold! Heat now",
    "Temp Cold - Heat the room",
    "Temp Slightly Cool - Add heat",
    "Temp Too Hot! Cool now",
    "Temp Warm - Ventilate / cool",
    "Temp Slightly Warm - Increase airflow",
    "DP Very Low! Humidify",
    "DP Low - Air may feel dry",
    "DP Muggy! Dehumidify now",
    "DP Very High - Vent/dehumidify",
    "DP High - Air may feel muggy",
    "Humidity Extremely Low! Humidify",
    "Humidity Very Low - Use humidifier",
    "Humidity Low - Consider humidifier",
    "Humidity Extremely High! Dehumidify",
    "Humidity Very High - Dehumidify",
    "Humidity High - Increase airflow",
    "SETTINGS",
    "SETTINGS",
    "SAVE & BACK",
    "TEMP OFFSET",
    "HUMID OFFSET",
    "NIGHT MODE",
    "C / F",
    "HEAD STATUS",
    "WI-FI",
    "TIME / DATE",
    "THEME COLOR",
    "MQTT",
    "AUTO NIGHT",
    "RESTART",
    "FACTORY\nRESET",
    "CO2\nCALLIBRATION",
    "ABOUT",
    "DOT\nINDICATORS",
    "ALERT\nBLINK",
    "VOC\nRELEARN",
    "BACKLIGHT",
    "WI-FI SETTINGS",
    "Wi-Fi status:",
    "To configure Wi-Fi:\n- Press ON / OFF button\n- Connect your phone or PC to network \"ProjectAura-Setup\".\n- Open http://192.168.4.1 in browser or scan QR code.\n- Select your home Wi-Fi network and enter the password.\n",
    "SSID:",
    "IP:",
    "FORGET\nWI-FI",
    "RECONNECT",
    "START AP",
    "MQTT SETTINGS",
    "MQTT status:",
    "To configure MQTT:\n- Connect Project Aura to WI-FI first\n- Open http://aura.local/mqtt in browser or scan QR code.",
    "Device IP:",
    "Broker IP:",
    "Topic:",
    "RECONNECT",
    "DATE & TIME",
    "TIME ZONE",
    "AUTO SYNC (NTP)",
    "SET TIME",
    "Hours:",
    "Minutes:",
    "SET DATE",
    "Day:",
    "Month:",
    "Year:",
    "TIME",
    "APPLY NOW",
    "RTC:",
    "WIFI:",
    "NTP:",
    "STATUS: ",
    "TEMP",
    "HUMIDITY",
    "PRESSURE",
    "WARMUP",
    "RESET VOC",
    "RESTART",
    "RESET",
    "CANCEL",
    "Reset VOC Calibration?",
    "VOC/NOx learning will restart.\nReadings may be unstable for a few hours.",
    "Restart Device?",
    "The device will reboot.\nReadings will pause briefly.",
    "Factory Reset?",
    "This clears Wi-Fi, offsets, themes,\nschedules and VOC state.\nThis cannot be undone.",
    "THEME:",
    "CUSTOM",
    "PRESETS",
    "EXAMPLE:",
    "To configure custom theme:\n- Connect Project Aura to WI-FI first\n- Open http://aura.local/theme in browser \nor scan QR code.\n- Save by pressing Back",
    "AUTO NIGHT MODE",
    "This feature activates \"Night Mode\" colors based on a schedule.\n- Set Start and End times below.\n- Toggle the switch to ON.\n- Manual Night Mode is disabled when Auto Night is ON.",
    "START TIME",
    "END TIME",
    "SCREEN BACKLIGHT",
    "Device monitors air quality while screen is off.\nSensors remain active. Touch to wake.",
    "SCHEDULED SLEEP",
    "POWER SAVING",
    "SLEEP AT",
    "WAKE AT",
    "ALWAYS ON",
    "30 SEC",
    "1 MIN",
    "5 MIN",
    "CO2 Calibration (Fresh Air)",
    "CALIBRATE\nCO2",
    "- ASC (Automatic Self-Calibration): ON by default.\n- Best when CO2 drops close to outdoor levels at least weekly\n(good ventilation / room unoccupied).\n- ASC adjusts slowly over days (not instantly).\n- With ASC ON, manual calibration is usually \nnot needed.",
    "- Power the device from a power bank.\n- Take it outdoors to clean fresh air.\n- Keep it away from people (breath), windows, cars, smoke, vents.\n- Let it run for 10 minutes (minimum 5).\n- Press Calibrate CO2 and keep the device still.\n- Manual calibration is for troubleshooting only.\n- Do not calibrate more than once every 6 months.\n- Calibration uses a 420 ppm reference.\n- Wrong conditions can make readings worse.",
    "TAP TO CONTINUE",
    "BOOT DIAGNOSTICS",
    "System",
    "Sensors",
    "App:",
    "MAC:",
    "Reset:",
    "Heap:",
    "Storage:",
    "I2C:",
    "Touch:",
    "SEN66:",
    "SFA30:",
    "PCF8523:",
    "Errors detected",
    "OK (config)",
    "OK (defaults)",
    "RECOVERED",
    "DETECTED",
    "FAIL",
    "STARTING",
    "NOT FOUND",
    "LOST",
    "AH very low! Humidify now",
    "AH low - Use humidifier",
    "AH high - Risk of mold",
    "AH very high! Mold grows fast",
    "Temperature affects comfort, productivity, and sleep quality. Thresholds based on ASHRAE Standard 55 (thermal comfort) and WHO housing recommendations. Optimal range helps maintain focus and prevents fatigue. Extremes cause discomfort, drowsiness, or difficulty concentrating. Prolonged exposure to poor conditions may affect health.",
    "Excellent: 20-25°C (68-77°F)\nIdeal range for comfort and productivity.",
    "Acceptable: 18-20°C or 25-26°C (64-68°F / 77-79°F)\nSlight discomfort possible.",
    "Uncomfortable: 16-18°C or 26-28°C (61-64°F / 79-82°F)\nNoticeable discomfort, lower productivity.",
    "Poor: <16°C or >28°C (<61°F / >82°F)\nSignificant discomfort, take action to adjust.",
    "VOC Index measures volatile organic compounds from paints, furniture, cleaning products, and cosmetics. Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased VOC concentration. Prolonged exposure may cause headaches, eye irritation, and fatigue. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=150\nNormal indoor air, no action needed",
    "Acceptable: 151-250\nSlight VOC elevation, consider ventilation",
    "Uncomfortable: 251-350\nNoticeable odors possible, ventilate recommended",
    "Poor: >350\nHeadaches and irritation likely, ventilate immediately",
    "NOx Index measures nitrogen oxides from combustion (traffic, gas stoves, heaters). Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased NOx. Exposure can irritate lungs and worsen asthma. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=50\nVery clean air",
    "Acceptable: 51-100\nSlight NOx elevation",
    "Uncomfortable: 101-200\nIrritation possible, ventilate recommended",
    "Poor: >200\nBreathing discomfort likely, ventilate immediately",
    "HCHO measures formaldehyde from furniture, pressed wood, fabrics, and some cleaners. Units in ppb. Higher levels can irritate eyes, nose, and throat. Prolonged exposure may affect breathing. Ventilate and reduce sources when elevated.",
    "Excellent: <30 ppb\nVery low formaldehyde",
    "Acceptable: 30-60 ppb\nLow level, keep ventilating",
    "Uncomfortable: 61-100 ppb\nIrritation possible, ventilate",
    "Poor: >100 ppb\nHealth risk, reduce sources and ventilate",
    "CO2 affects alertness, decision-making, and sleep quality. Outdoor air is about 420 ppm. Higher indoor levels indicate poor ventilation. Sustained exposure above 1000 ppm can reduce focus and cause drowsiness. Ventilate when elevated.",
    "Excellent: <800 ppm\nGood ventilation, optimal performance",
    "Acceptable: 800-1000 ppm\nSlightly elevated, consider airing",
    "Uncomfortable: 1001-1500 ppm\nDrowsiness possible, ventilate",
    "Poor: >1500 ppm\nHeadaches and low focus likely, ventilate now",
    "PM2.5 measures fine particles from combustion, smoke, and indoor sources. These particles penetrate deep into lungs and can affect heart health. High levels can worsen asthma and cause irritation. Use filtration and reduce sources when elevated.",
    "Excellent: <=12 ug/m3\nVery clean air",
    "Acceptable: 12-35 ug/m3\nSlight elevation, consider filtration",
    "Uncomfortable: 35-55 ug/m3\nRespiratory irritation possible",
    "Poor: >55 ug/m3\nHealth risk, reduce exposure",
    "PM10 measures coarse particles like dust, pollen, and road debris. High levels can irritate eyes, nose, and throat and worsen respiratory symptoms. Ventilate with clean air and reduce dust sources when elevated.",
    "Excellent: <=54 ug/m3\nClean air",
    "Acceptable: 54-154 ug/m3\nSome dust, sensitive groups may react",
    "Uncomfortable: 154-254 ug/m3\nIrritation likely, reduce exposure",
    "Poor: >254 ug/m3\nHigh pollution, stay indoors",
    "3h pressure trend shows short-term changes that can signal approaching weather. Rapid drops often precede storms; rapid rises indicate clearing. Use the delta below to judge how fast conditions are changing.",
    "Excellent: <1 hPa\nStable pressure",
    "Acceptable: 1-3 hPa\nMinor change",
    "Uncomfortable: 3-6 hPa\nNoticeable change",
    "Poor: >6 hPa\nRapid change, weather shift likely",
    "24h pressure trend shows daily change. Large swings suggest unstable weather; steady values mean stable conditions. Use the delta below to judge intensity.",
    "Excellent: <2 hPa\nStable conditions",
    "Acceptable: 2-6 hPa\nSmall change",
    "Uncomfortable: 6-10 hPa\nSignificant change",
    "Poor: >10 hPa\nMajor change, storms possible"
};

constexpr const char *kStringsDe[] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "Index",
    "HCHO",
    "AQI",
    "Initialisiere...",
    "Frische Luft - Alles gut",
    "Ausgezeichnet",
    "Gut",
    "Mittel",
    "Schlecht",
    "AUS",
    "AN",
    "OK",
    "ERR",
    "SYNC",
    "Verbunden",
    "AP Modus",
    "Fehler",
    "Verbinde...",
    "Deaktiviert",
    "Kein WLAN",
    "Verbunden",
    "Fehler",
    "Wiederholen (10m)",
    "Wiederholen (1h)",
    "Verbinde...",
    "AN / AUS",
    "Alle 6h",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 Sehr hoch! Jetzt lüften",
    "CO2 Hoch - Bald lüften",
    "CO2 Steigt - Lüften erwägen",
    "PM2.5 Sehr hoch! Reinigen - Rauch stoppen",
    "PM2.5 Hoch - Reinigen - Quelle prüfen",
    "PM2.5 Erhöht - Reiniger erwägen",
    "PM10 Sehr hoch! Reinigen - Quelle prüfen",
    "PM10 Hoch - Reinigen - Staub reduzieren",
    "PM10 Erhöht - Staub reduzieren",
    "HCHO Sehr hoch! Lüften - Quelle weg",
    "HCHO Hoch - Lüften - Quelle weg",
    "HCHO Erkannt - Quellen prüfen",
    "VOC Sehr hoch! Quelle finden - lüften",
    "VOC Hoch - Mehr lüften",
    "NOx Sehr hoch! Quelle stoppen - lüften",
    "NOx Hoch - Abzug nutzen - Quelle prüfen",
    "NOx Erhöht - Herd/Außen prüfen",
    "Zu kalt! Heizen",
    "Kalt - Raum heizen",
    "Etwas kühl - Mehr Wärme",
    "Zu heiß! Kühlen",
    "Warm - Lüften / kühlen",
    "Etwas warm - Mehr Luft",
    "DP Sehr niedrig! Befeuchten",
    "DP Niedrig - Luft kann trocken sein",
    "DP Schwül! Entfeuchten",
    "DP Sehr hoch - Lüften/entfeuchten",
    "DP Hoch - Luft kann schwül sein",
    "Luftfeuchte Extrem niedrig! Befeuchten",
    "Luftfeuchte Sehr niedrig - Befeuchter",
    "Luftfeuchte Niedrig - Befeuchter erwägen",
    "Luftfeuchte Extrem hoch! Entfeuchten",
    "Luftfeuchte Sehr hoch - Entfeuchten",
    "Luftfeuchte Hoch - Mehr Luft",
    "EINSTELL",
    "EINSTELL",
    "ZURÜCK",
    "TEMP-KORR.",
    "FEUCHT-KORR.",
    "NACHTMODUS",
    "C / F",
    "HEAD STATUS",
    "WI-FI",
    "ZEIT / DATUM",
    "THEME FARBE",
    "MQTT",
    "AUTO NACHT",
    "NEUSTART",
    "WERKS\nRESET",
    "CO2\nKALIBRIEREN",
    "INFO",
    "PUNKT\nANZEIGE",
    "ALARM\nBLINK",
    "VOC\nNEU LERNEN",
    "HINTERLICHT",
    "WLAN EINSTELLUNGEN",
    "WLAN Status:",
    "WLAN einrichten:\n- ON / OFF drücken\n- Mit \"ProjectAura-Setup\" verbinden\n- http://192.168.4.1 öffnen oder QR-Code scannen\n- Heimnetz wählen und Passwort eingeben\n",
    "SSID:",
    "IP:",
    "WLAN\nLÖSCHEN",
    "VERBINDEN",
    "AP START",
    "MQTT EINSTELLUNGEN",
    "MQTT Status:",
    "MQTT einrichten:\n- Project Aura zuerst mit WLAN verbinden\n- http://aura.local/mqtt öffnen oder QR-Code scannen",
    "Gerät IP:",
    "Broker IP:",
    "Topic:",
    "VERBINDEN",
    "DATUM & ZEIT",
    "ZEITZONE",
    "AUTO SYNC (NTP)",
    "ZEIT SETZEN",
    "Stunden:",
    "Minuten:",
    "DATUM SETZEN",
    "Tag:",
    "Monat:",
    "Jahr:",
    "ZEIT",
    "JETZT ANWENDEN",
    "RTC:",
    "WLAN:",
    "NTP:",
    "STATUS: ",
    "TEMP",
    "LUFTFEUCHTE",
    "DRUCK",
    "WARMLAUF",
    "VOC RESET",
    "NEUSTART",
    "RESET",
    "ABBRECHEN",
    "VOC-Kalibrierung zurücksetzen?",
    "VOC/NOx-Lernen wird neu gestartet.\nWerte können einige Stunden instabil sein.",
    "Gerät neu starten?",
    "Das Gerät wird neu gestartet.\nMesswerte pausieren kurz.",
    "Werkseinstellungen zurücksetzen?",
    "Dies löscht WLAN, Offsets, Themes,\nZeitpläne und VOC-Status.\nDies kann nicht rückgängig gemacht werden.",
    "THEME:",
    "EIGEN",
    "VORLAGEN",
    "BEISPIEL:",
    "Custom-Theme einrichten:\n- Project Aura zuerst mit WLAN verbinden\n- http://aura.local/theme öffnen oder QR-Code scannen\n- Mit Zurück speichern",
    "AUTO NACHTMODUS",
    "Diese Funktion aktiviert \"Nachtmodus\" nach Zeitplan.\n- Start- und Endzeit einstellen.\n- Schalter auf AN.\n- Manueller Nachtmodus ist deaktiviert,\n  wenn Auto Nacht aktiv ist.",
    "STARTZEIT",
    "ENDZEIT",
    "HINTERLICHT",
    "Gerät überwacht Luftqualität bei ausgeschaltetem Bildschirm.\nSensoren bleiben aktiv. Berühren zum Aufwecken.",
    "GEPLANTER SCHLAF",
    "ENERGIESPAREN",
    "SCHLAFEN UM",
    "AUFWACHEN UM",
    "IMMER AN",
    "30 SEK",
    "1 MIN",
    "5 MIN",
    "CO2 Kalibrierung (Frischluft)",
    "KALIBRIEREN\nCO2",
    "- ASC (Auto-Selbstkalibrierung): Standardmäßig AN.\n- Am besten, wenn CO2 mind. wöchentlich nahe Außenluft fällt\n  (gute Lüftung / Raum unbesetzt).\n- ASC passt sich langsam über Tage an (nicht sofort).\n- Mit ASC AN ist manuelle Kalibrierung meist nicht nötig.",
    "- Gerät mit Powerbank betreiben.\n- Nach draußen an frische Luft bringen.\n- Fern von Menschen (Atem), Fenstern, Autos, Rauch, Lüftungen.\n- 10 Minuten laufen lassen (mind. 5).\n- CO2 kalibrieren drücken und Gerät ruhig halten.\n- Manuelle Kalibrierung nur zur Fehlersuche.\n- Nicht öfter als alle 6 Monate kalibrieren.\n- Kalibrierung nutzt 420 ppm Referenz.\n- Falsche Bedingungen verschlechtern die Messung.",
    "TIPPE ZUM FORTFAHREN",
    "BOOT-DIAGNOSE",
    "System",
    "Sensoren",
    "App:",
    "MAC:",
    "Reset:",
    "Heap:",
    "Speicher:",
    "I2C:",
    "Touch:",
    "SEN66:",
    "SFA30:",
    "PCF8523:",
    "Fehler erkannt",
    "OK (Konfig)",
    "OK (Standard)",
    "WIEDER OK",
    "ERKANNT",
    "FEHLER",
    "STARTET...",
    "NICHT GEFUNDEN",
    "VERLOREN",
    "AH sehr niedrig! Befeuchten",
    "AH niedrig - Luftbefeuchter",
    "AH hoch - Schimmelrisiko",
    "AH sehr hoch! Schimmel wächst",
    "Temperature affects comfort, productivity, and sleep quality. Thresholds based on ASHRAE Standard 55 (thermal comfort) and WHO housing recommendations. Optimal range helps maintain focus and prevents fatigue. Extremes cause discomfort, drowsiness, or difficulty concentrating. Prolonged exposure to poor conditions may affect health.",
    "Excellent: 20-25°C (68-77°F)\nIdeal range for comfort and productivity.",
    "Acceptable: 18-20°C or 25-26°C (64-68°F / 77-79°F)\nSlight discomfort possible.",
    "Uncomfortable: 16-18°C or 26-28°C (61-64°F / 79-82°F)\nNoticeable discomfort, lower productivity.",
    "Poor: <16°C or >28°C (<61°F / >82°F)\nSignificant discomfort, take action to adjust.",
    "VOC Index measures volatile organic compounds from paints, furniture, cleaning products, and cosmetics. Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased VOC concentration. Prolonged exposure may cause headaches, eye irritation, and fatigue. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=150\nNormal indoor air, no action needed",
    "Acceptable: 151-250\nSlight VOC elevation, consider ventilation",
    "Uncomfortable: 251-350\nNoticeable odors possible, ventilate recommended",
    "Poor: >350\nHeadaches and irritation likely, ventilate immediately",
    "NOx Index measures nitrogen oxides from combustion (traffic, gas stoves, heaters). Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased NOx. Exposure can irritate lungs and worsen asthma. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=50\nVery clean air",
    "Acceptable: 51-100\nSlight NOx elevation",
    "Uncomfortable: 101-200\nIrritation possible, ventilate recommended",
    "Poor: >200\nBreathing discomfort likely, ventilate immediately",
    "HCHO measures formaldehyde from furniture, pressed wood, fabrics, and some cleaners. Units in ppb. Higher levels can irritate eyes, nose, and throat. Prolonged exposure may affect breathing. Ventilate and reduce sources when elevated.",
    "Excellent: <30 ppb\nVery low formaldehyde",
    "Acceptable: 30-60 ppb\nLow level, keep ventilating",
    "Uncomfortable: 61-100 ppb\nIrritation possible, ventilate",
    "Poor: >100 ppb\nHealth risk, reduce sources and ventilate",
    "CO2 affects alertness, decision-making, and sleep quality. Outdoor air is about 420 ppm. Higher indoor levels indicate poor ventilation. Sustained exposure above 1000 ppm can reduce focus and cause drowsiness. Ventilate when elevated.",
    "Excellent: <800 ppm\nGood ventilation, optimal performance",
    "Acceptable: 800-1000 ppm\nSlightly elevated, consider airing",
    "Uncomfortable: 1001-1500 ppm\nDrowsiness possible, ventilate",
    "Poor: >1500 ppm\nHeadaches and low focus likely, ventilate now",
    "PM2.5 measures fine particles from combustion, smoke, and indoor sources. These particles penetrate deep into lungs and can affect heart health. High levels can worsen asthma and cause irritation. Use filtration and reduce sources when elevated.",
    "Excellent: <=12 ug/m3\nVery clean air",
    "Acceptable: 12-35 ug/m3\nSlight elevation, consider filtration",
    "Uncomfortable: 35-55 ug/m3\nRespiratory irritation possible",
    "Poor: >55 ug/m3\nHealth risk, reduce exposure",
    "PM10 measures coarse particles like dust, pollen, and road debris. High levels can irritate eyes, nose, and throat and worsen respiratory symptoms. Ventilate with clean air and reduce dust sources when elevated.",
    "Excellent: <=54 ug/m3\nClean air",
    "Acceptable: 54-154 ug/m3\nSome dust, sensitive groups may react",
    "Uncomfortable: 154-254 ug/m3\nIrritation likely, reduce exposure",
    "Poor: >254 ug/m3\nHigh pollution, stay indoors",
    "3h pressure trend shows short-term changes that can signal approaching weather. Rapid drops often precede storms; rapid rises indicate clearing. Use the delta below to judge how fast conditions are changing.",
    "Excellent: <1 hPa\nStable pressure",
    "Acceptable: 1-3 hPa\nMinor change",
    "Uncomfortable: 3-6 hPa\nNoticeable change",
    "Poor: >6 hPa\nRapid change, weather shift likely",
    "24h pressure trend shows daily change. Large swings suggest unstable weather; steady values mean stable conditions. Use the delta below to judge intensity.",
    "Excellent: <2 hPa\nStable conditions",
    "Acceptable: 2-6 hPa\nSmall change",
    "Uncomfortable: 6-10 hPa\nSignificant change",
    "Poor: >10 hPa\nMajor change, storms possible"
};

static_assert(sizeof(kStringsDe) / sizeof(kStringsDe[0]) ==
              static_cast<size_t>(TextId::Count),
              "UiStrings: DE table size mismatch");

constexpr const char *kStringsFr[static_cast<size_t>(TextId::Count)] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "Index",
    "HCHO",
    "AQI",
    "Initialisation",
    "Air frais - Tout va bien",
    "Excellent",
    "Bon",
    "Moyen",
    "Mauvais",
    "OFF",
    "ON",
    "OK",
    "ERR",
    "SYNC",
    "Connecté",
    "Mode AP",
    "Erreur",
    "Connexion",
    "Désactivé",
    "Pas de Wi-Fi",
    "Connecté",
    "Erreur",
    "Nouvel essai (10m)",
    "Nouvel essai (1h)",
    "Connexion...",
    "ON / OFF",
    "Toutes les 6h",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 très élevé! Aérez maintenant",
    "CO2 élevé - Aérez bientôt",
    "CO2 en hausse - Pensez à aérer",
    "PM2.5 très élevé! Purifiez - stop fumée",
    "PM2.5 élevé - Purifiez - source?",
    "PM2.5 élevé - Pensez purificateur",
    "PM10 très élevé! Purifiez - source?",
    "PM10 élevé - Purifiez - réduisez poussière",
    "PM10 modéré - Réduisez poussière",
    "HCHO très élevé! Aérez - supprimez source",
    "HCHO élevé - Aérez - supprimez source",
    "HCHO détecté - Vérifiez sources",
    "VOC très élevé! Trouvez source - aérez",
    "VOC élevé - Augmentez ventilation",
    "NOx très élevé! Stop source - aérez",
    "NOx élevé - Utilisez hotte - source",
    "NOx modéré - Vérifiez cuisine/dehors",
    "Temp trop basse! Chauffez",
    "Temp basse - Chauffez la pièce",
    "Temp un peu basse - Plus de chaleur",
    "Temp trop haute! Refroidissez",
    "Temp chaude - Aérez / refroidissez",
    "Temp un peu chaude - Plus d'air",
    "DP très bas! Humidifiez",
    "DP bas - Air peut sembler sec",
    "DP lourd! Déshumidifiez",
    "DP très haut - Aérez/déshumidifiez",
    "DP haut - Air peut sembler lourd",
    "Humidité très basse! Humidifiez",
    "Humidité très basse - Humidificateur",
    "Humidité basse - Pensez humidifier",
    "Humidité très élevée! Déshumidifiez",
    "Humidité très élevée - Déshumidifiez",
    "Humidité élevée - Plus d'air",
    "RÉGLAGES",
    "RÉGLAGES",
    "RETOUR",
    "CORR. TEMP",
    "CORR. HUM",
    "MODE NUIT",
    "C / F",
    "ÉTAT HEAD",
    "WI-FI",
    "HEURE / DATE",
    "COULEUR THÈME",
    "MQTT",
    "AUTO NUIT",
    "REDÉMARRER",
    "RESET\nUSINE",
    "CO2\nCALIBRATION",
    "INFO",
    "POINTS\nINDICATEURS",
    "ALERTE\nCLIGNOTER",
    "VOC\nRÉAPPRENDRE",
    "ÉCLAIRAGE",
    "RÉGLAGES WI-FI",
    "Statut Wi-Fi:",
    "Pour configurer le Wi-Fi:\n- Appuyez sur ON / OFF\n- Connectez votre téléphone ou PC à \"ProjectAura-Setup\".\n- Ouvrez http://192.168.4.1 ou scannez le QR.\n- Choisissez votre réseau Wi-Fi et entrez le mot de passe.\n",
    "SSID:",
    "IP:",
    "OUBLIER\nWI-FI",
    "RECONNECTER",
    "DÉMARRER AP",
    "RÉGLAGES MQTT",
    "Statut MQTT:",
    "Pour configurer MQTT:\n- Connectez Project Aura au WI-FI d'abord\n- Ouvrez http://aura.local/mqtt ou scannez le QR.",
    "IP appareil:",
    "IP broker:",
    "Topic:",
    "RECONNECTER",
    "DATE & HEURE",
    "FUSEAU HORAIRE",
    "SYNC AUTO (NTP)",
    "RÉGLER HEURE",
    "Heures:",
    "Minutes:",
    "RÉGLER DATE",
    "Jour:",
    "Mois:",
    "Année:",
    "HEURE",
    "APPLIQUER",
    "RTC:",
    "WIFI:",
    "NTP:",
    "ÉTAT: ",
    "TEMP",
    "HUMIDITÉ",
    "PRESSION",
    "CHAUFFE",
    "RESET VOC",
    "REDÉMARRER",
    "RESET",
    "ANNULER",
    "Réinitialiser VOC?",
    "L'apprentissage VOC/NOx redémarre.\nMesures instables quelques heures.",
    "Redémarrer l'appareil?",
    "L'appareil va redémarrer.\nMesures en pause brièvement.",
    "Réinit. usine?",
    "Efface Wi-Fi, offsets, thèmes,\nplannings et état VOC.\nAction irréversible.",
    "THÈME:",
    "PERSO",
    "PRÉSETS",
    "EXEMPLE:",
    "Pour thème personnalisé:\n- Connectez Project Aura au WI-FI d'abord\n- Ouvrez http://aura.local/theme\n  ou scannez le QR.\n- Enregistrer via Retour",
    "MODE NUIT AUTO",
    "Active les couleurs \"Mode Nuit\" par horaire.\n- Réglez début et fin.\n- Mettez l'interrupteur sur ON.\n- Mode Nuit manuel désactivé\n  quand Auto Nuit est ON.",
    "HEURE DÉBUT",
    "HEURE FIN",
    "ÉCLAIRAGE ÉCRAN",
    "Mesure l'air écran éteint.\nCapteurs actifs. Touchez pour réveiller.",
    "SOMMEIL PROGRAMMÉ",
    "ÉCONOMIE ÉNERGIE",
    "DORMIR À",
    "RÉVEIL À",
    "TOUJOURS",
    "30 SEC",
    "1 MIN",
    "5 MIN",
    "Calibrage CO2 (Air frais)",
    "CALIBRER\nCO2",
    "- ASC (Auto Self-Calibration): ON par défaut.\n- Idéal si CO2 baisse proche extérieur chaque semaine\n  (bonne ventilation / pièce vide).\n- ASC ajuste lentement (jours, pas instantané).\n- Avec ASC ON, calibration manuelle\n  généralement inutile.",
    "- Alimentez avec power bank.\n- Sortez à l'air frais.\n- Éloignez de personnes, fenêtres, voitures, fumée, sorties.\n- Laissez 10 min (min 5).\n- Appuyez Calibrer CO2 et ne bougez pas.\n- Calibration manuelle pour dépannage.\n- Pas plus d'une fois / 6 mois.\n- Référence 420 ppm.\n- Mauvaises conditions dégradent les mesures.",
    "TOUCHEZ POUR CONTINUER",
    "DIAGNOSTIC BOOT",
    "Système",
    "Capteurs",
    "App:",
    "MAC:",
    "Reset:",
    "Heap:",
    "Stockage:",
    "I2C:",
    "Touch:",
    "SEN66:",
    "SFA30:",
    "PCF8523:",
    "Erreurs détectées",
    "OK (config)",
    "OK (défaut)",
    "RÉTABLI",
    "DÉTECTÉ",
    "ÉCHEC",
    "DÉMARRAGE",
    "NON TROUVÉ",
    "PERDU",
    "AH très bas! Humidifiez",
    "AH bas - Utiliser humidif.",
    "AH élevé - Risque de moisissure",
    "AH très élevé! Moisissure rapide",
    "Temperature affects comfort, productivity, and sleep quality. Thresholds based on ASHRAE Standard 55 (thermal comfort) and WHO housing recommendations. Optimal range helps maintain focus and prevents fatigue. Extremes cause discomfort, drowsiness, or difficulty concentrating. Prolonged exposure to poor conditions may affect health.",
    "Excellent: 20-25°C (68-77°F)\nIdeal range for comfort and productivity.",
    "Acceptable: 18-20°C or 25-26°C (64-68°F / 77-79°F)\nSlight discomfort possible.",
    "Uncomfortable: 16-18°C or 26-28°C (61-64°F / 79-82°F)\nNoticeable discomfort, lower productivity.",
    "Poor: <16°C or >28°C (<61°F / >82°F)\nSignificant discomfort, take action to adjust.",
    "VOC Index measures volatile organic compounds from paints, furniture, cleaning products, and cosmetics. Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased VOC concentration. Prolonged exposure may cause headaches, eye irritation, and fatigue. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=150\nNormal indoor air, no action needed",
    "Acceptable: 151-250\nSlight VOC elevation, consider ventilation",
    "Uncomfortable: 251-350\nNoticeable odors possible, ventilate recommended",
    "Poor: >350\nHeadaches and irritation likely, ventilate immediately",
    "NOx Index measures nitrogen oxides from combustion (traffic, gas stoves, heaters). Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased NOx. Exposure can irritate lungs and worsen asthma. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=50\nVery clean air",
    "Acceptable: 51-100\nSlight NOx elevation",
    "Uncomfortable: 101-200\nIrritation possible, ventilate recommended",
    "Poor: >200\nBreathing discomfort likely, ventilate immediately",
    "HCHO measures formaldehyde from furniture, pressed wood, fabrics, and some cleaners. Units in ppb. Higher levels can irritate eyes, nose, and throat. Prolonged exposure may affect breathing. Ventilate and reduce sources when elevated.",
    "Excellent: <30 ppb\nVery low formaldehyde",
    "Acceptable: 30-60 ppb\nLow level, keep ventilating",
    "Uncomfortable: 61-100 ppb\nIrritation possible, ventilate",
    "Poor: >100 ppb\nHealth risk, reduce sources and ventilate",
    "CO2 affects alertness, decision-making, and sleep quality. Outdoor air is about 420 ppm. Higher indoor levels indicate poor ventilation. Sustained exposure above 1000 ppm can reduce focus and cause drowsiness. Ventilate when elevated.",
    "Excellent: <800 ppm\nGood ventilation, optimal performance",
    "Acceptable: 800-1000 ppm\nSlightly elevated, consider airing",
    "Uncomfortable: 1001-1500 ppm\nDrowsiness possible, ventilate",
    "Poor: >1500 ppm\nHeadaches and low focus likely, ventilate now",
    "PM2.5 measures fine particles from combustion, smoke, and indoor sources. These particles penetrate deep into lungs and can affect heart health. High levels can worsen asthma and cause irritation. Use filtration and reduce sources when elevated.",
    "Excellent: <=12 ug/m3\nVery clean air",
    "Acceptable: 12-35 ug/m3\nSlight elevation, consider filtration",
    "Uncomfortable: 35-55 ug/m3\nRespiratory irritation possible",
    "Poor: >55 ug/m3\nHealth risk, reduce exposure",
    "PM10 measures coarse particles like dust, pollen, and road debris. High levels can irritate eyes, nose, and throat and worsen respiratory symptoms. Ventilate with clean air and reduce dust sources when elevated.",
    "Excellent: <=54 ug/m3\nClean air",
    "Acceptable: 54-154 ug/m3\nSome dust, sensitive groups may react",
    "Uncomfortable: 154-254 ug/m3\nIrritation likely, reduce exposure",
    "Poor: >254 ug/m3\nHigh pollution, stay indoors",
    "3h pressure trend shows short-term changes that can signal approaching weather. Rapid drops often precede storms; rapid rises indicate clearing. Use the delta below to judge how fast conditions are changing.",
    "Excellent: <1 hPa\nStable pressure",
    "Acceptable: 1-3 hPa\nMinor change",
    "Uncomfortable: 3-6 hPa\nNoticeable change",
    "Poor: >6 hPa\nRapid change, weather shift likely",
    "24h pressure trend shows daily change. Large swings suggest unstable weather; steady values mean stable conditions. Use the delta below to judge intensity.",
    "Excellent: <2 hPa\nStable conditions",
    "Acceptable: 2-6 hPa\nSmall change",
    "Uncomfortable: 6-10 hPa\nSignificant change",
    "Poor: >10 hPa\nMajor change, storms possible"
};

static_assert(sizeof(kStringsFr) / sizeof(kStringsFr[0]) ==
              static_cast<size_t>(TextId::Count),
              "UiStrings: FR table size mismatch");

constexpr const char *kStringsIt[static_cast<size_t>(TextId::Count)] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "Index",
    "HCHO",
    "AQI",
    "Inizializzazione",
    "Aria fresca - Tutto ok",
    "Eccellente",
    "Buono",
    "Moderato",
    "Scarso",
    "OFF",
    "ON",
    "OK",
    "ERR",
    "SYNC",
    "Connesso",
    "Modalità AP",
    "Errore",
    "Connessione",
    "Disattivato",
    "No Wi-Fi",
    "Connesso",
    "Errore",
    "Riprova (10m)",
    "Riprova (1h)",
    "Connessione...",
    "ON / OFF",
    "Ogni 6h",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 molto alto! Arieggia ora",
    "CO2 alto - Arieggia presto",
    "CO2 in aumento - Considera ventilazione",
    "PM2.5 molto alto! Purifica - stop fumo",
    "PM2.5 alto - Purifica - controlla fonte",
    "PM2.5 elevato - Valuta purificatore",
    "PM10 molto alto! Purifica - controlla fonte",
    "PM10 alto - Purifica - riduci polvere",
    "PM10 elevato - Purifica - riduci polvere",
    "HCHO molto alto! Arieggia - rimuovi fonte",
    "HCHO alto - Arieggia - rimuovi fonte",
    "HCHO rilevato - Controlla fonti",
    "VOC molto alto! Trova fonte - arieggia",
    "VOC alto - Aumenta ventilazione",
    "NOx molto alto! Ferma fonte - arieggia",
    "NOx alto - Usa cappa - controlla fonte",
    "NOx elevato - Controlla cucina/esterno",
    "Temp troppo bassa! Riscalda",
    "Temp bassa - Riscalda la stanza",
    "Temp un po' bassa - Più calore",
    "Temp troppo alta! Raffredda",
    "Temp alta - Arieggia / raffredda",
    "Temp un po' alta - Più aria",
    "DP molto basso! Umidifica",
    "DP basso - Aria può sembrare secca",
    "DP afoso! Deumidifica",
    "DP molto alto - Arieggia/deumidifica",
    "DP alto - Aria può essere afosa",
    "Umidità molto bassa! Umidifica",
    "Umidità molto bassa - Usa umidificatore",
    "Umidità bassa - Valuta umidificatore",
    "Umidità molto alta! Deumidifica",
    "Umidità molto alta - Deumidifica",
    "Umidità alta - Più ventilazione",
    "IMPOSTAZIONI",
    "IMPOST",
    "INDIETRO",
    "OFFSET TEMP",
    "OFFSET UMID",
    "MODO NOTTE",
    "C / F",
    "STATO HEAD",
    "WI-FI",
    "ORA / DATA",
    "COLORE TEMA",
    "MQTT",
    "AUTO NOTTE",
    "RIAVVIA",
    "RESET\nFABBRICA",
    "CO2\nCALIBRAZIONE",
    "INFO",
    "PUNTI\nINDICATORI",
    "ALLARME\nLAMPEGGIA",
    "VOC\nRIAPPRENDI",
    "RETROILL.",
    "IMPOSTAZIONI WI-FI",
    "Stato Wi-Fi:",
    "Per configurare il Wi-Fi:\n- Premi ON / OFF\n- Connetti telefono o PC a \"ProjectAura-Setup\".\n- Apri http://192.168.4.1 o scansiona QR.\n- Seleziona la rete Wi-Fi e inserisci la password.\n",
    "SSID:",
    "IP:",
    "DIMENTICA\nWI-FI",
    "RICOLLEGA",
    "AVVIA AP",
    "IMPOSTAZIONI MQTT",
    "Stato MQTT:",
    "Per configurare MQTT:\n- Connetti Project Aura al WI-FI prima\n- Apri http://aura.local/mqtt o scansiona QR.",
    "IP dispositivo:",
    "IP broker:",
    "Topic:",
    "RICOLLEGA",
    "DATA E ORA",
    "FUSO ORARIO",
    "SYNC AUTO (NTP)",
    "IMPOSTA ORA",
    "Ore:",
    "Minuti:",
    "IMPOSTA DATA",
    "Giorno:",
    "Mese:",
    "Anno:",
    "ORA",
    "APPLICA",
    "RTC:",
    "WIFI:",
    "NTP:",
    "STATO: ",
    "TEMP",
    "UMIDITÀ",
    "PRESSIONE",
    "RISCALD.",
    "RESET VOC",
    "RIAVVIA",
    "RESET",
    "ANNULLA",
    "Reset calibrazione VOC?",
    "L'apprendimento VOC/NOx riparte.\nLetture instabili per alcune ore.",
    "Riavvia dispositivo?",
    "Il dispositivo si riavvia.\nLetture in pausa brevemente.",
    "Reset di fabbrica?",
    "Cancella Wi-Fi, offset, temi,\nprogrammi e stato VOC.\nAzione irreversibile.",
    "TEMA:",
    "PERSON.",
    "PRESET",
    "ESEMPIO:",
    "Per tema personalizzato:\n- Connetti Project Aura al WI-FI prima\n- Apri http://aura.local/theme\n  o scansiona QR.\n- Salva con Indietro",
    "MODO NOTTE AUTO",
    "Attiva colori \"Modo Notte\" a orario.\n- Imposta inizio e fine.\n- Interruttore su ON.\n- Modo Notte manuale disattivato\n  quando Auto Notte è ON.",
    "ORA INIZIO",
    "ORA FINE",
    "RETROILLUMINAZ.",
    "Misura aria a schermo spento.\nSensori attivi. Tocca per svegliare.",
    "SONNO PROGRAM.",
    "RISPARMIO",
    "DORMI ALLE",
    "SVEGLIA ALLE",
    "SEMPRE",
    "30 SEC",
    "1 MIN",
    "5 MIN",
    "Calibrazione CO2 (Aria fresca)",
    "CALIBRA\nCO2",
    "- ASC (Auto Self-Calibration): ON per default.\n- Ideale se CO2 scende vicino esterno ogni settimana\n  (buona ventilazione / stanza vuota).\n- ASC regola lentamente (giorni, non istantaneo).\n- Con ASC ON, calibrazione manuale\n  di solito non necessaria.",
    "- Alimenta con power bank.\n- Porta all'aperto in aria pulita.\n- Lontano da persone, finestre, auto, fumo, bocchette.\n- Lascia 10 min (min 5).\n- Premi Calibra CO2 e non muovere.\n- Calibrazione manuale solo diagnostica.\n- Non più di una volta / 6 mesi.\n- Riferimento 420 ppm.\n- Condizioni errate peggiorano letture.",
    "TOCCA PER CONTINUARE",
    "DIAGNOSTICA BOOT",
    "Sistema",
    "Sensori",
    "App:",
    "MAC:",
    "Reset:",
    "Heap:",
    "Memoria:",
    "I2C:",
    "Touch:",
    "SEN66:",
    "SFA30:",
    "PCF8523:",
    "Errori rilevati",
    "OK (config)",
    "OK (default)",
    "RECUPERATO",
    "RILEVATO",
    "FALLITO",
    "AVVIO",
    "NON TROVATO",
    "PERSO",
    "AH molto basso! Umidifica",
    "AH basso - Usa umidificatore",
    "AH alto - Rischio muffa",
    "AH molto alto! Muffa rapida",
    "Temperature affects comfort, productivity, and sleep quality. Thresholds based on ASHRAE Standard 55 (thermal comfort) and WHO housing recommendations. Optimal range helps maintain focus and prevents fatigue. Extremes cause discomfort, drowsiness, or difficulty concentrating. Prolonged exposure to poor conditions may affect health.",
    "Excellent: 20-25°C (68-77°F)\nIdeal range for comfort and productivity.",
    "Acceptable: 18-20°C or 25-26°C (64-68°F / 77-79°F)\nSlight discomfort possible.",
    "Uncomfortable: 16-18°C or 26-28°C (61-64°F / 79-82°F)\nNoticeable discomfort, lower productivity.",
    "Poor: <16°C or >28°C (<61°F / >82°F)\nSignificant discomfort, take action to adjust.",
    "VOC Index measures volatile organic compounds from paints, furniture, cleaning products, and cosmetics. Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased VOC concentration. Prolonged exposure may cause headaches, eye irritation, and fatigue. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=150\nNormal indoor air, no action needed",
    "Acceptable: 151-250\nSlight VOC elevation, consider ventilation",
    "Uncomfortable: 251-350\nNoticeable odors possible, ventilate recommended",
    "Poor: >350\nHeadaches and irritation likely, ventilate immediately",
    "NOx Index measures nitrogen oxides from combustion (traffic, gas stoves, heaters). Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased NOx. Exposure can irritate lungs and worsen asthma. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=50\nVery clean air",
    "Acceptable: 51-100\nSlight NOx elevation",
    "Uncomfortable: 101-200\nIrritation possible, ventilate recommended",
    "Poor: >200\nBreathing discomfort likely, ventilate immediately",
    "HCHO measures formaldehyde from furniture, pressed wood, fabrics, and some cleaners. Units in ppb. Higher levels can irritate eyes, nose, and throat. Prolonged exposure may affect breathing. Ventilate and reduce sources when elevated.",
    "Excellent: <30 ppb\nVery low formaldehyde",
    "Acceptable: 30-60 ppb\nLow level, keep ventilating",
    "Uncomfortable: 61-100 ppb\nIrritation possible, ventilate",
    "Poor: >100 ppb\nHealth risk, reduce sources and ventilate",
    "CO2 affects alertness, decision-making, and sleep quality. Outdoor air is about 420 ppm. Higher indoor levels indicate poor ventilation. Sustained exposure above 1000 ppm can reduce focus and cause drowsiness. Ventilate when elevated.",
    "Excellent: <800 ppm\nGood ventilation, optimal performance",
    "Acceptable: 800-1000 ppm\nSlightly elevated, consider airing",
    "Uncomfortable: 1001-1500 ppm\nDrowsiness possible, ventilate",
    "Poor: >1500 ppm\nHeadaches and low focus likely, ventilate now",
    "PM2.5 measures fine particles from combustion, smoke, and indoor sources. These particles penetrate deep into lungs and can affect heart health. High levels can worsen asthma and cause irritation. Use filtration and reduce sources when elevated.",
    "Excellent: <=12 ug/m3\nVery clean air",
    "Acceptable: 12-35 ug/m3\nSlight elevation, consider filtration",
    "Uncomfortable: 35-55 ug/m3\nRespiratory irritation possible",
    "Poor: >55 ug/m3\nHealth risk, reduce exposure",
    "PM10 measures coarse particles like dust, pollen, and road debris. High levels can irritate eyes, nose, and throat and worsen respiratory symptoms. Ventilate with clean air and reduce dust sources when elevated.",
    "Excellent: <=54 ug/m3\nClean air",
    "Acceptable: 54-154 ug/m3\nSome dust, sensitive groups may react",
    "Uncomfortable: 154-254 ug/m3\nIrritation likely, reduce exposure",
    "Poor: >254 ug/m3\nHigh pollution, stay indoors",
    "3h pressure trend shows short-term changes that can signal approaching weather. Rapid drops often precede storms; rapid rises indicate clearing. Use the delta below to judge how fast conditions are changing.",
    "Excellent: <1 hPa\nStable pressure",
    "Acceptable: 1-3 hPa\nMinor change",
    "Uncomfortable: 3-6 hPa\nNoticeable change",
    "Poor: >6 hPa\nRapid change, weather shift likely",
    "24h pressure trend shows daily change. Large swings suggest unstable weather; steady values mean stable conditions. Use the delta below to judge intensity.",
    "Excellent: <2 hPa\nStable conditions",
    "Acceptable: 2-6 hPa\nSmall change",
    "Uncomfortable: 6-10 hPa\nSignificant change",
    "Poor: >10 hPa\nMajor change, storms possible"
};

static_assert(sizeof(kStringsIt) / sizeof(kStringsIt[0]) ==
              static_cast<size_t>(TextId::Count),
              "UiStrings: IT table size mismatch");

constexpr const char *kStringsPtBr[static_cast<size_t>(TextId::Count)] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "Index",
    "HCHO",
    "AQI",
    "Inicializando",
    "Ar fresco - Tudo ok",
    "Excelente",
    "Bom",
    "Moderado",
    "Ruim",
    "OFF",
    "ON",
    "OK",
    "ERR",
    "SYNC",
    "Conectado",
    "Modo AP",
    "Erro",
    "Conectando",
    "Desativado",
    "Sem Wi-Fi",
    "Conectado",
    "Erro",
    "Nova tentativa (10m)",
    "Nova tentativa (1h)",
    "Conectando...",
    "ON / OFF",
    "A cada 6h",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 muito alto! Ventile agora",
    "CO2 alto - Ventile logo",
    "CO2 subindo - Considere ventilar",
    "PM2.5 muito alto! Purifique - pare fumaça",
    "PM2.5 alto - Purifique - verifique fonte",
    "PM2.5 elevado - Considere purificador",
    "PM10 muito alto! Purifique - verifique fonte",
    "PM10 alto - Purifique - reduza poeira",
    "PM10 elevado - Purifique - reduza poeira",
    "HCHO muito alto! Ventile - remova fonte",
    "HCHO alto - Ventile - remova fonte",
    "HCHO detectado - Verifique fontes",
    "VOC muito alto! Ache fonte - ventile",
    "VOC alto - Aumente ventilação",
    "NOx muito alto! Pare fonte - ventile",
    "NOx alto - Use exaustor - verifique fonte",
    "NOx elevado - Verifique fogão/externo",
    "Temp muito baixa! Aqueça agora",
    "Temp baixa - Aqueça o ambiente",
    "Temp um pouco baixa - Mais calor",
    "Temp muito alta! Resfrie agora",
    "Temp alta - Ventile / resfrie",
    "Temp um pouco alta - Mais ar",
    "DP muito baixo! Umidifique",
    "DP baixo - Ar pode parecer seco",
    "DP abafado! Desumidifique",
    "DP muito alto - Ventile/desumidifique",
    "DP alto - Ar pode ficar abafado",
    "Umidade muito baixa! Umidifique",
    "Umidade muito baixa - Use umidificador",
    "Umidade baixa - Considere umidificador",
    "Umidade muito alta! Desumidifique",
    "Umidade muito alta - Desumidifique",
    "Umidade alta - Mais ventilação",
    "CONFIGURAÇÕES",
    "CONFIG",
    "VOLTAR",
    "OFFSET TEMP",
    "OFFSET UMID",
    "MODO NOITE",
    "C / F",
    "STATUS HEAD",
    "WI-FI",
    "HORA / DATA",
    "COR TEMA",
    "MQTT",
    "AUTO NOITE",
    "REINICIAR",
    "RESET\nFÁBRICA",
    "CO2\nCALIBRAÇÃO",
    "SOBRE",
    "PONTOS\nINDICADORES",
    "ALERTA\nPISCAR",
    "VOC\nREAPRENDER",
    "RETROILUM.",
    "CONFIG. WI-FI",
    "Status Wi-Fi:",
    "Para configurar Wi-Fi:\n- Pressione ON / OFF\n- Conecte o celular ou PC à rede \"ProjectAura-Setup\".\n- Abra http://192.168.4.1 ou escaneie o QR.\n- Selecione sua rede Wi-Fi e digite a senha.\n",
    "SSID:",
    "IP:",
    "ESQUECER\nWI-FI",
    "RECONECTAR",
    "INICIAR AP",
    "CONFIG. MQTT",
    "Status MQTT:",
    "Para configurar MQTT:\n- Conecte Project Aura ao WI-FI primeiro\n- Abra http://aura.local/mqtt ou escaneie o QR.",
    "IP dispositivo:",
    "IP broker:",
    "Tópico:",
    "RECONECTAR",
    "DATA E HORA",
    "FUSO HORÁRIO",
    "SYNC AUTO (NTP)",
    "AJUSTAR HORA",
    "Horas:",
    "Minutos:",
    "AJUSTAR DATA",
    "Dia:",
    "Mês:",
    "Ano:",
    "HORA",
    "APLICAR",
    "RTC:",
    "WIFI:",
    "NTP:",
    "STATUS: ",
    "TEMP",
    "UMIDADE",
    "PRESSÃO",
    "AQUEC.",
    "RESET VOC",
    "REINICIAR",
    "RESET",
    "CANCELAR",
    "Reset calibração VOC?",
    "Aprendizado VOC/NOx reinicia.\nLeituras instáveis por algumas horas.",
    "Reiniciar dispositivo?",
    "O dispositivo irá reiniciar.\nLeituras pausam brevemente.",
    "Reset de fábrica?",
    "Apaga Wi-Fi, offsets, temas,\nagendas e estado VOC.\nAção irreversível.",
    "TEMA:",
    "PERS.",
    "PRESET",
    "EXEMPLO:",
    "Para tema personalizado:\n- Conecte Project Aura ao WI-FI primeiro\n- Abra http://aura.local/theme\n  ou escaneie o QR.\n- Salve com Voltar",
    "MODO NOITE AUTO",
    "Este recurso ativa cores do \"Modo Noite\" por horário.\n- Defina início e fim.\n- Ligue o interruptor.\n- Modo Noite manual desativado\n  quando Auto Noite está ON.",
    "HORA INÍCIO",
    "HORA FIM",
    "LUZ DE FUNDO",
    "Dispositivo monitora ar com tela apagada.\nSensores permanecem ativos. Toque para acordar.",
    "SONO PROGRAM.",
    "ECONOMIA",
    "DORMIR ÀS",
    "ACORDAR ÀS",
    "SEMPRE",
    "30 SEG",
    "1 MIN",
    "5 MIN",
    "Calibração CO2 (Ar fresco)",
    "CALIBRAR\nCO2",
    "- ASC (Auto Self-Calibration): ON por padrão.\n- Ideal se CO2 cai perto do externo semanalmente\n  (boa ventilação / sala vazia).\n- ASC ajusta lentamente (dias, não instantâneo).\n- Com ASC ON, calibração manual\n  geralmente não é necessária.",
    "- Alimente com power bank.\n- Leve para fora em ar limpo.\n- Longe de pessoas, janelas, carros, fumaça, saídas.\n- Aguarde 10 min (mín 5).\n- Pressione Calibrar CO2 e não mova.\n- Calibração manual só para diagnóstico.\n- No máximo 1x / 6 meses.\n- Referência 420 ppm.\n- Condições erradas pioram leituras.",
    "TOQUE PARA CONTINUAR",
    "DIAGNÓSTICO BOOT",
    "Sistema",
    "Sensores",
    "App:",
    "MAC:",
    "Reset:",
    "Heap:",
    "Armazenamento:",
    "I2C:",
    "Touch:",
    "SEN66:",
    "SFA30:",
    "PCF8523:",
    "Erros detectados",
    "OK (config)",
    "OK (padrão)",
    "RECUPERADO",
    "DETECTADO",
    "FALHA",
    "INICIANDO",
    "NÃO ENCONTRADO",
    "PERDIDO",
    "AH muito baixo! Umidifique",
    "AH baixo - Use umidificador",
    "AH alto - Risco de mofo",
    "AH muito alto! Mofo rápido",
    "Temperature affects comfort, productivity, and sleep quality. Thresholds based on ASHRAE Standard 55 (thermal comfort) and WHO housing recommendations. Optimal range helps maintain focus and prevents fatigue. Extremes cause discomfort, drowsiness, or difficulty concentrating. Prolonged exposure to poor conditions may affect health.",
    "Excellent: 20-25°C (68-77°F)\nIdeal range for comfort and productivity.",
    "Acceptable: 18-20°C or 25-26°C (64-68°F / 77-79°F)\nSlight discomfort possible.",
    "Uncomfortable: 16-18°C or 26-28°C (61-64°F / 79-82°F)\nNoticeable discomfort, lower productivity.",
    "Poor: <16°C or >28°C (<61°F / >82°F)\nSignificant discomfort, take action to adjust.",
    "VOC Index measures volatile organic compounds from paints, furniture, cleaning products, and cosmetics. Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased VOC concentration. Prolonged exposure may cause headaches, eye irritation, and fatigue. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=150\nNormal indoor air, no action needed",
    "Acceptable: 151-250\nSlight VOC elevation, consider ventilation",
    "Uncomfortable: 251-350\nNoticeable odors possible, ventilate recommended",
    "Poor: >350\nHeadaches and irritation likely, ventilate immediately",
    "NOx Index measures nitrogen oxides from combustion (traffic, gas stoves, heaters). Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased NOx. Exposure can irritate lungs and worsen asthma. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=50\nVery clean air",
    "Acceptable: 51-100\nSlight NOx elevation",
    "Uncomfortable: 101-200\nIrritation possible, ventilate recommended",
    "Poor: >200\nBreathing discomfort likely, ventilate immediately",
    "HCHO measures formaldehyde from furniture, pressed wood, fabrics, and some cleaners. Units in ppb. Higher levels can irritate eyes, nose, and throat. Prolonged exposure may affect breathing. Ventilate and reduce sources when elevated.",
    "Excellent: <30 ppb\nVery low formaldehyde",
    "Acceptable: 30-60 ppb\nLow level, keep ventilating",
    "Uncomfortable: 61-100 ppb\nIrritation possible, ventilate",
    "Poor: >100 ppb\nHealth risk, reduce sources and ventilate",
    "CO2 affects alertness, decision-making, and sleep quality. Outdoor air is about 420 ppm. Higher indoor levels indicate poor ventilation. Sustained exposure above 1000 ppm can reduce focus and cause drowsiness. Ventilate when elevated.",
    "Excellent: <800 ppm\nGood ventilation, optimal performance",
    "Acceptable: 800-1000 ppm\nSlightly elevated, consider airing",
    "Uncomfortable: 1001-1500 ppm\nDrowsiness possible, ventilate",
    "Poor: >1500 ppm\nHeadaches and low focus likely, ventilate now",
    "PM2.5 measures fine particles from combustion, smoke, and indoor sources. These particles penetrate deep into lungs and can affect heart health. High levels can worsen asthma and cause irritation. Use filtration and reduce sources when elevated.",
    "Excellent: <=12 ug/m3\nVery clean air",
    "Acceptable: 12-35 ug/m3\nSlight elevation, consider filtration",
    "Uncomfortable: 35-55 ug/m3\nRespiratory irritation possible",
    "Poor: >55 ug/m3\nHealth risk, reduce exposure",
    "PM10 measures coarse particles like dust, pollen, and road debris. High levels can irritate eyes, nose, and throat and worsen respiratory symptoms. Ventilate with clean air and reduce dust sources when elevated.",
    "Excellent: <=54 ug/m3\nClean air",
    "Acceptable: 54-154 ug/m3\nSome dust, sensitive groups may react",
    "Uncomfortable: 154-254 ug/m3\nIrritation likely, reduce exposure",
    "Poor: >254 ug/m3\nHigh pollution, stay indoors",
    "3h pressure trend shows short-term changes that can signal approaching weather. Rapid drops often precede storms; rapid rises indicate clearing. Use the delta below to judge how fast conditions are changing.",
    "Excellent: <1 hPa\nStable pressure",
    "Acceptable: 1-3 hPa\nMinor change",
    "Uncomfortable: 3-6 hPa\nNoticeable change",
    "Poor: >6 hPa\nRapid change, weather shift likely",
    "24h pressure trend shows daily change. Large swings suggest unstable weather; steady values mean stable conditions. Use the delta below to judge intensity.",
    "Excellent: <2 hPa\nStable conditions",
    "Acceptable: 2-6 hPa\nSmall change",
    "Uncomfortable: 6-10 hPa\nSignificant change",
    "Poor: >10 hPa\nMajor change, storms possible"
};

static_assert(sizeof(kStringsPtBr) / sizeof(kStringsPtBr[0]) ==
              static_cast<size_t>(TextId::Count),
              "UiStrings: PT-BR table size mismatch");

constexpr const char *kStringsNl[static_cast<size_t>(TextId::Count)] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "Index",
    "HCHO",
    "AQI",
    "Initialiseren",
    "Frisse lucht - Alles goed",
    "Uitstekend",
    "Goed",
    "Matig",
    "Slecht",
    "UIT",
    "AAN",
    "OK",
    "ERR",
    "SYNC",
    "Verbonden",
    "AP-modus",
    "Fout",
    "Verbinden",
    "Uitgeschakeld",
    "Geen Wi-Fi",
    "Verbonden",
    "Fout",
    "Opnieuw (10m)",
    "Opnieuw (1h)",
    "Verbinden...",
    "AAN / UIT",
    "Elke 6h",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 zeer hoog! Ventileer nu",
    "CO2 hoog - Ventileer snel",
    "CO2 stijgt - Overweeg ventilatie",
    "PM2.5 zeer hoog! Zuiver - stop rook",
    "PM2.5 hoog - Zuiver - check bron",
    "PM2.5 verhoogd - Overweeg filter",
    "PM10 zeer hoog! Zuiver - check bron",
    "PM10 hoog - Zuiver - minder stof",
    "PM10 verhoogd - Zuiver - minder stof",
    "HCHO zeer hoog! Ventileer - bron weg",
    "HCHO hoog - Ventileer - bron weg",
    "HCHO gedetecteerd - Check bronnen",
    "VOC zeer hoog! Bron zoeken - ventileer",
    "VOC hoog - Meer ventilatie",
    "NOx zeer hoog! Stop bron - ventileer",
    "NOx hoog - Gebruik afzuiging",
    "NOx verhoogd - Check koken/buiten",
    "Temp te koud! Verwarm nu",
    "Temp koud - Verwarm ruimte",
    "Temp wat koel - Meer warmte",
    "Temp te warm! Koel nu",
    "Temp warm - Ventileer / koel",
    "Temp wat warm - Meer lucht",
    "DP zeer laag! Bevochtig",
    "DP laag - Lucht kan droog zijn",
    "DP benauwd! Ontvochtig",
    "DP zeer hoog - Ventileer/ontvochtig",
    "DP hoog - Lucht kan benauwd zijn",
    "Luchtvocht. zeer laag! Bevochtig",
    "Luchtvocht. zeer laag - Gebruik bevochtiger",
    "Luchtvocht. laag - Overweeg bevochtiger",
    "Luchtvocht. zeer hoog! Ontvochtig",
    "Luchtvocht. zeer hoog - Ontvochtig",
    "Luchtvocht. hoog - Meer ventilatie",
    "INSTELLINGEN",
    "INSTELL",
    "TERUG",
    "TEMP OFFSET",
    "VOCHT OFFSET",
    "NACHTMODUS",
    "C / F",
    "HEAD STATUS",
    "WI-FI",
    "TIJD / DATUM",
    "THEMA KLEUR",
    "MQTT",
    "AUTO NACHT",
    "HERSTART",
    "FABRIEKS\nRESET",
    "CO2\nKALIBREREN",
    "INFO",
    "PUNTEN\nINDICATOREN",
    "ALARM\nKNIPPEREN",
    "VOC\nOPNIEUW LEREN",
    "ACHTERL.",
    "WI-FI INSTELL.",
    "Wi-Fi status:",
    "Wi-Fi instellen:\n- Druk op AAN / UIT\n- Verbind telefoon/pc met \"ProjectAura-Setup\".\n- Open http://192.168.4.1 of scan QR.\n- Kies wifi-netwerk en voer wachtwoord in.\n",
    "SSID:",
    "IP:",
    "WIS\nWI-FI",
    "HERBIND",
    "START AP",
    "MQTT INSTELL.",
    "MQTT status:",
    "MQTT instellen:\n- Verbind Project Aura eerst met WI-FI\n- Open http://aura.local/mqtt of scan QR.",
    "Apparaat IP:",
    "Broker IP:",
    "Topic:",
    "HERBIND",
    "DATUM & TIJD",
    "TIJDZONE",
    "AUTO SYNC (NTP)",
    "TIJD INST.",
    "Uur:",
    "Minuten:",
    "DATUM INST.",
    "Dag:",
    "Maand:",
    "Jaar:",
    "TIJD",
    "TOEPASSEN",
    "RTC:",
    "WIFI:",
    "NTP:",
    "STATUS: ",
    "TEMP",
    "LUCHTVOCHT.",
    "DRUK",
    "OPWARMEN",
    "RESET VOC",
    "HERSTART",
    "RESET",
    "ANNULEREN",
    "VOC kalibratie resetten?",
    "VOC/NOx leren start opnieuw.\nMetingen kunnen uren instabiel zijn.",
    "Apparaat herstarten?",
    "Apparaat zal herstarten.\nMetingen pauzeren kort.",
    "Fabrieksreset?",
    "Wist Wi-Fi, offsets, thema's,\nroosters en VOC-status.\nDit kan niet ongedaan.",
    "THEMA:",
    "PERS.",
    "PRESETS",
    "VOORBEELD:",
    "Voor aangepast thema:\n- Verbind Project Aura eerst met WI-FI\n- Open http://aura.local/theme\n  of scan QR.\n- Opslaan via Terug",
    "AUTO NACHTMODUS",
    "Activeert \"Nachtmodus\" via schema.\n- Stel start en eind in.\n- Zet schakelaar op AAN.\n- Handmatige nachtmodus uit\n  wanneer Auto Nacht AAN is.",
    "STARTTIJD",
    "EINDTIJD",
    "SCHERM LICHT",
    "Apparaat meet lucht met scherm uit.\nSensoren blijven actief. Tik om te wekken.",
    "SLAAPSCHEMA",
    "ENERGIE",
    "SLAAP OM",
    "WAKKER OM",
    "ALTIJD",
    "30 SEC",
    "1 MIN",
    "5 MIN",
    "CO2 kalibratie (Frisse lucht)",
    "KALIBREREN\nCO2",
    "- ASC (Auto Self-Calibration): AAN standaard.\n- Beste als CO2 wekelijks dicht bij buiten komt\n  (goede ventilatie / ruimte leeg).\n- ASC past langzaam aan (dagen, niet direct).\n- Met ASC AAN is handmatige\n  kalibratie meestal niet nodig.",
    "- Voed via powerbank.\n- Neem mee naar buiten in frisse lucht.\n- Weg van mensen, ramen, auto's, rook, vents.\n- Laat 10 min draaien (min 5).\n- Druk Kalibreer CO2 en beweeg niet.\n- Handmatige kalibratie alleen diagnose.\n- Max 1x / 6 maanden.\n- Referentie 420 ppm.\n- Foute omstandigheden verslechteren metingen.",
    "TIK OM DOOR TE GAAN",
    "BOOTDIAGNOSTIEK",
    "Systeem",
    "Sensoren",
    "App:",
    "MAC:",
    "Reset:",
    "Heap:",
    "Opslag:",
    "I2C:",
    "Touch:",
    "SEN66:",
    "SFA30:",
    "PCF8523:",
    "Fouten gedetecteerd",
    "OK (config)",
    "OK (standaard)",
    "HERSTELD",
    "GEDETECTEERD",
    "MISLUKT",
    "STARTEN",
    "NIET GEVONDEN",
    "VERLOREN",
    "AH zeer laag! Bevochtig",
    "AH laag - Gebruik bevochtiger",
    "AH hoog - Schimmelrisico",
    "AH zeer hoog! Schimmel snel",
    "Temperature affects comfort, productivity, and sleep quality. Thresholds based on ASHRAE Standard 55 (thermal comfort) and WHO housing recommendations. Optimal range helps maintain focus and prevents fatigue. Extremes cause discomfort, drowsiness, or difficulty concentrating. Prolonged exposure to poor conditions may affect health.",
    "Excellent: 20-25°C (68-77°F)\nIdeal range for comfort and productivity.",
    "Acceptable: 18-20°C or 25-26°C (64-68°F / 77-79°F)\nSlight discomfort possible.",
    "Uncomfortable: 16-18°C or 26-28°C (61-64°F / 79-82°F)\nNoticeable discomfort, lower productivity.",
    "Poor: <16°C or >28°C (<61°F / >82°F)\nSignificant discomfort, take action to adjust.",
    "VOC Index measures volatile organic compounds from paints, furniture, cleaning products, and cosmetics. Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased VOC concentration. Prolonged exposure may cause headaches, eye irritation, and fatigue. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=150\nNormal indoor air, no action needed",
    "Acceptable: 151-250\nSlight VOC elevation, consider ventilation",
    "Uncomfortable: 251-350\nNoticeable odors possible, ventilate recommended",
    "Poor: >350\nHeadaches and irritation likely, ventilate immediately",
    "NOx Index measures nitrogen oxides from combustion (traffic, gas stoves, heaters). Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased NOx. Exposure can irritate lungs and worsen asthma. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=50\nVery clean air",
    "Acceptable: 51-100\nSlight NOx elevation",
    "Uncomfortable: 101-200\nIrritation possible, ventilate recommended",
    "Poor: >200\nBreathing discomfort likely, ventilate immediately",
    "HCHO measures formaldehyde from furniture, pressed wood, fabrics, and some cleaners. Units in ppb. Higher levels can irritate eyes, nose, and throat. Prolonged exposure may affect breathing. Ventilate and reduce sources when elevated.",
    "Excellent: <30 ppb\nVery low formaldehyde",
    "Acceptable: 30-60 ppb\nLow level, keep ventilating",
    "Uncomfortable: 61-100 ppb\nIrritation possible, ventilate",
    "Poor: >100 ppb\nHealth risk, reduce sources and ventilate",
    "CO2 affects alertness, decision-making, and sleep quality. Outdoor air is about 420 ppm. Higher indoor levels indicate poor ventilation. Sustained exposure above 1000 ppm can reduce focus and cause drowsiness. Ventilate when elevated.",
    "Excellent: <800 ppm\nGood ventilation, optimal performance",
    "Acceptable: 800-1000 ppm\nSlightly elevated, consider airing",
    "Uncomfortable: 1001-1500 ppm\nDrowsiness possible, ventilate",
    "Poor: >1500 ppm\nHeadaches and low focus likely, ventilate now",
    "PM2.5 measures fine particles from combustion, smoke, and indoor sources. These particles penetrate deep into lungs and can affect heart health. High levels can worsen asthma and cause irritation. Use filtration and reduce sources when elevated.",
    "Excellent: <=12 ug/m3\nVery clean air",
    "Acceptable: 12-35 ug/m3\nSlight elevation, consider filtration",
    "Uncomfortable: 35-55 ug/m3\nRespiratory irritation possible",
    "Poor: >55 ug/m3\nHealth risk, reduce exposure",
    "PM10 measures coarse particles like dust, pollen, and road debris. High levels can irritate eyes, nose, and throat and worsen respiratory symptoms. Ventilate with clean air and reduce dust sources when elevated.",
    "Excellent: <=54 ug/m3\nClean air",
    "Acceptable: 54-154 ug/m3\nSome dust, sensitive groups may react",
    "Uncomfortable: 154-254 ug/m3\nIrritation likely, reduce exposure",
    "Poor: >254 ug/m3\nHigh pollution, stay indoors",
    "3h pressure trend shows short-term changes that can signal approaching weather. Rapid drops often precede storms; rapid rises indicate clearing. Use the delta below to judge how fast conditions are changing.",
    "Excellent: <1 hPa\nStable pressure",
    "Acceptable: 1-3 hPa\nMinor change",
    "Uncomfortable: 3-6 hPa\nNoticeable change",
    "Poor: >6 hPa\nRapid change, weather shift likely",
    "24h pressure trend shows daily change. Large swings suggest unstable weather; steady values mean stable conditions. Use the delta below to judge intensity.",
    "Excellent: <2 hPa\nStable conditions",
    "Acceptable: 2-6 hPa\nSmall change",
    "Uncomfortable: 6-10 hPa\nSignificant change",
    "Poor: >10 hPa\nMajor change, storms possible"
};

static_assert(sizeof(kStringsNl) / sizeof(kStringsNl[0]) ==
              static_cast<size_t>(TextId::Count),
              "UiStrings: NL table size mismatch");

constexpr const char *kStringsZh[static_cast<size_t>(TextId::Count)] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "指数",
    "HCHO",
    "AQI",
    "初始化中",
    "空气清新 - 一切正常",
    "优秀",
    "良好",
    "一般",
    "较差",
    "关",
    "开",
    "OK",
    "错误",
    "同步",
    "已连接",
    "AP模式",
    "错误",
    "连接中",
    "已禁用",
    "无Wi-Fi",
    "已连接",
    "错误",
    "重试(10m)",
    "重试(1h)",
    "连接中...",
    "开 / 关",
    "每6小时",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 很高! 立即通风",
    "CO2 高 - 尽快通风",
    "CO2 上升 - 建议通风",
    "PM2.5 很高! 净化 - 停止烟雾",
    "PM2.5 高 - 净化 - 检查来源",
    "PM2.5 偏高 - 建议净化器",
    "PM10 很高! 净化 - 检查来源",
    "PM10 高 - 净化 - 减少扬尘",
    "PM10 偏高 - 净化 - 减少扬尘",
    "HCHO 很高! 通风 - 移除来源",
    "HCHO 高 - 通风 - 移除来源",
    "检测到HCHO - 检查来源",
    "VOC 很高! 查找来源 - 通风",
    "VOC 高 - 增加通风",
    "NOx 很高! 停止来源 - 通风",
    "NOx 高 - 使用油烟机 - 检查来源",
    "NOx 偏高 - 检查炉灶/室外",
    "温度太低! 立即加热",
    "温度偏低 - 加热房间",
    "温度略低 - 增加供暖",
    "温度太高! 立即降温",
    "温度偏高 - 通风/降温",
    "温度略高 - 增加通风",
    "DP 很低! 加湿",
    "DP 低 - 空气可能干燥",
    "DP 闷热! 立即除湿",
    "DP 很高 - 通风/除湿",
    "DP 高 - 空气可能闷",
    "湿度极低! 加湿",
    "湿度很低 - 使用加湿器",
    "湿度偏低 - 考虑加湿器",
    "湿度极高! 除湿",
    "湿度很高 - 除湿",
    "湿度偏高 - 增加通风",
    "设置",
    "设置",
    "保存并返回",
    "温度偏移",
    "湿度偏移",
    "夜间模式",
    "C / F",
    "探头状态",
    "Wi-Fi",
    "时间/日期",
    "主题颜色",
    "MQTT",
    "自动夜间",
    "重启",
    "恢复\n出厂",
    "CO2\n校准",
    "关于",
    "指示\n灯",
    "警报\n闪烁",
    "VOC\n重新学习",
    "背光",
    "Wi-Fi 设置",
    "Wi-Fi 状态:",
    "配置 Wi-Fi:\n- 按下 开/关\n- 用手机或电脑连接 \"ProjectAura-Setup\".\n- 打开 http://192.168.4.1 或扫描二维码.\n- 选择家庭 Wi-Fi 并输入密码.\n",
    "SSID:",
    "IP:",
    "忘记\nWI-FI",
    "重新连接",
    "启动AP",
    "MQTT 设置",
    "MQTT 状态:",
    "配置 MQTT:\n- 先将 Project Aura 连接到 WI-FI\n- 打开 http://aura.local/mqtt 或扫描二维码.",
    "设备 IP:",
    "Broker IP:",
    "Topic:",
    "重新连接",
    "日期和时间",
    "时区",
    "自动同步 (NTP)",
    "设置时间",
    "小时:",
    "分钟:",
    "设置日期",
    "日:",
    "月:",
    "年:",
    "时间",
    "立即应用",
    "RTC:",
    "WIFI:",
    "NTP:",
    "状态: ",
    "温度",
    "湿度",
    "气压",
    "预热",
    "重置 VOC",
    "重启",
    "重置",
    "取消",
    "重置 VOC 校准?",
    "VOC/NOx 学习将重启.\n读数可能会不稳定数小时.",
    "重启设备?",
    "设备将重启.\n读数会短暂停止.",
    "恢复出厂设置?",
    "将清除 Wi-Fi、偏移、主题、\n计划和 VOC 状态.\n此操作不可恢复.",
    "主题:",
    "自定义",
    "预设",
    "示例:",
    "自定义主题:\n- 先将 Project Aura 连接到 WI-FI\n- 打开 http://aura.local/theme\n  或扫描二维码\n- 按 返回 保存",
    "自动夜间模式",
    "此功能按时间表启用\"夜间模式\".\n- 设置开始和结束时间\n- 将开关置为开\n- 自动夜间开启时\n  手动夜间将禁用",
    "开始时间",
    "结束时间",
    "屏幕背光",
    "屏幕关闭时仍监测空气质量.\n传感器保持工作, 触摸唤醒.",
    "定时休眠",
    "省电",
    "休眠于",
    "唤醒于",
    "常亮",
    "30 秒",
    "1 分",
    "5 分",
    "CO2 校准(新鲜空气)",
    "校准\nCO2",
    "- ASC (自动自校准): 默认开启.\n- 适合每周至少一次 CO2 降至室外水平\n  (通风良好/房间无人).\n- ASC 调整缓慢(按天, 非即时).\n- 开启 ASC 时通常不需要\n  手动校准.",
    "- 使用移动电源供电.\n- 带到室外新鲜空气处.\n- 远离人(呼吸)、窗户、汽车、烟雾、出风口.\n- 运行 10 分钟(至少 5 分钟).\n- 按 校准 CO2 并保持静止.\n- 手动校准仅用于排查问题.\n- 6 个月最多一次.\n- 校准使用 420 ppm 参考.\n- 条件不当会使读数变差.",
    "点击继续",
    "启动诊断",
    "系统",
    "传感器",
    "应用:",
    "MAC:",
    "重置:",
    "堆:",
    "存储:",
    "I2C:",
    "触控:",
    "SEN66:",
    "SFA30:",
    "PCF8523:",
    "检测到错误",
    "OK (配置)",
    "OK (默认)",
    "已恢复",
    "已检测",
    "失败",
    "启动中",
    "未找到",
    "丢失",
    "AH 很低! 立即加湿",
    "AH 低 - 使用加湿器",
    "AH 高 - 霉菌风险",
    "AH 很高! 霉菌迅速生长",
    "Temperature affects comfort, productivity, and sleep quality. Thresholds based on ASHRAE Standard 55 (thermal comfort) and WHO housing recommendations. Optimal range helps maintain focus and prevents fatigue. Extremes cause discomfort, drowsiness, or difficulty concentrating. Prolonged exposure to poor conditions may affect health.",
    "Excellent: 20-25°C (68-77°F)\nIdeal range for comfort and productivity.",
    "Acceptable: 18-20°C or 25-26°C (64-68°F / 77-79°F)\nSlight discomfort possible.",
    "Uncomfortable: 16-18°C or 26-28°C (61-64°F / 79-82°F)\nNoticeable discomfort, lower productivity.",
    "Poor: <16°C or >28°C (<61°F / >82°F)\nSignificant discomfort, take action to adjust.",
    "VOC Index measures volatile organic compounds from paints, furniture, cleaning products, and cosmetics. Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased VOC concentration. Prolonged exposure may cause headaches, eye irritation, and fatigue. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=150\nNormal indoor air, no action needed",
    "Acceptable: 151-250\nSlight VOC elevation, consider ventilation",
    "Uncomfortable: 251-350\nNoticeable odors possible, ventilate recommended",
    "Poor: >350\nHeadaches and irritation likely, ventilate immediately",
    "NOx Index measures nitrogen oxides from combustion (traffic, gas stoves, heaters). Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased NOx. Exposure can irritate lungs and worsen asthma. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=50\nVery clean air",
    "Acceptable: 51-100\nSlight NOx elevation",
    "Uncomfortable: 101-200\nIrritation possible, ventilate recommended",
    "Poor: >200\nBreathing discomfort likely, ventilate immediately",
    "HCHO measures formaldehyde from furniture, pressed wood, fabrics, and some cleaners. Units in ppb. Higher levels can irritate eyes, nose, and throat. Prolonged exposure may affect breathing. Ventilate and reduce sources when elevated.",
    "Excellent: <30 ppb\nVery low formaldehyde",
    "Acceptable: 30-60 ppb\nLow level, keep ventilating",
    "Uncomfortable: 61-100 ppb\nIrritation possible, ventilate",
    "Poor: >100 ppb\nHealth risk, reduce sources and ventilate",
    "CO2 affects alertness, decision-making, and sleep quality. Outdoor air is about 420 ppm. Higher indoor levels indicate poor ventilation. Sustained exposure above 1000 ppm can reduce focus and cause drowsiness. Ventilate when elevated.",
    "Excellent: <800 ppm\nGood ventilation, optimal performance",
    "Acceptable: 800-1000 ppm\nSlightly elevated, consider airing",
    "Uncomfortable: 1001-1500 ppm\nDrowsiness possible, ventilate",
    "Poor: >1500 ppm\nHeadaches and low focus likely, ventilate now",
    "PM2.5 measures fine particles from combustion, smoke, and indoor sources. These particles penetrate deep into lungs and can affect heart health. High levels can worsen asthma and cause irritation. Use filtration and reduce sources when elevated.",
    "Excellent: <=12 ug/m3\nVery clean air",
    "Acceptable: 12-35 ug/m3\nSlight elevation, consider filtration",
    "Uncomfortable: 35-55 ug/m3\nRespiratory irritation possible",
    "Poor: >55 ug/m3\nHealth risk, reduce exposure",
    "PM10 measures coarse particles like dust, pollen, and road debris. High levels can irritate eyes, nose, and throat and worsen respiratory symptoms. Ventilate with clean air and reduce dust sources when elevated.",
    "Excellent: <=54 ug/m3\nClean air",
    "Acceptable: 54-154 ug/m3\nSome dust, sensitive groups may react",
    "Uncomfortable: 154-254 ug/m3\nIrritation likely, reduce exposure",
    "Poor: >254 ug/m3\nHigh pollution, stay indoors",
    "3h pressure trend shows short-term changes that can signal approaching weather. Rapid drops often precede storms; rapid rises indicate clearing. Use the delta below to judge how fast conditions are changing.",
    "Excellent: <1 hPa\nStable pressure",
    "Acceptable: 1-3 hPa\nMinor change",
    "Uncomfortable: 3-6 hPa\nNoticeable change",
    "Poor: >6 hPa\nRapid change, weather shift likely",
    "24h pressure trend shows daily change. Large swings suggest unstable weather; steady values mean stable conditions. Use the delta below to judge intensity.",
    "Excellent: <2 hPa\nStable conditions",
    "Acceptable: 2-6 hPa\nSmall change",
    "Uncomfortable: 6-10 hPa\nSignificant change",
    "Poor: >10 hPa\nMajor change, storms possible"
};

static_assert(sizeof(kStringsZh) / sizeof(kStringsZh[0]) ==
              static_cast<size_t>(TextId::Count),
              "UiStrings: ZH table size mismatch");

constexpr const char *kStringsEs[static_cast<size_t>(TextId::Count)] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "Index",
    "HCHO",
    "AQI",
    "Inicializando",
    "Aire fresco - Todo bien",
    "Excelente",
    "Bueno",
    "Moderado",
    "Malo",
    "OFF",
    "ON",
    "OK",
    "ERR",
    "SYNC",
    "Conectado",
    "Modo AP",
    "Error",
    "Conectando",
    "Desactivado",
    "Sin WiFi",
    "Conectado",
    "Error",
    "Reintento (10m)",
    "Reintento (1h)",
    "Conectando...",
    "ON / OFF",
    "Cada 6h",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 muy alto! Ventila ahora",
    "CO2 alto - Ventila pronto",
    "CO2 subiendo - Considera ventilar",
    "PM2.5 muy alto! Purifica - detén humo",
    "PM2.5 alto - Purifica - revisa origen",
    "PM2.5 elevado - Considera purificador",
    "PM10 muy alto! Purifica - revisa origen",
    "PM10 alto - Purifica - reduce polvo",
    "PM10 elevado - Purifica - reduce polvo",
    "HCHO muy alto! Ventila - elimina fuente",
    "HCHO alto - Ventila - elimina fuente",
    "HCHO detectado - Revisa fuentes",
    "VOC muy alto! Busca fuente - ventila",
    "VOC alto - Aumenta ventilación",
    "NOx muy alto! Detén fuente - ventila",
    "NOx alto - Usa extractor - revisa origen",
    "NOx elevado - Revisa cocina/exterior",
    "Temp muy baja! Calienta ahora",
    "Temp baja - Calienta la sala",
    "Temp algo baja - Más calor",
    "Temp muy alta! Enfría ahora",
    "Temp alta - Ventila / enfría",
    "Temp algo alta - Más aire",
    "DP muy bajo! Humidifica",
    "DP bajo - Aire puede sentirse seco",
    "DP bochornoso! Deshumidifica",
    "DP muy alto - Ventila/deshumidifica",
    "DP alto - Aire puede sentirse bochornoso",
    "Humedad extremadamente baja! Humidifica",
    "Humedad muy baja - Usa humidificador",
    "Humedad baja - Considera humidificador",
    "Humedad extremadamente alta! Deshumidifica",
    "Humedad muy alta - Deshumidifica",
    "Humedad alta - Aumenta ventilación",
    "AJUSTES",
    "AJUSTES",
    "ATRÁS",
    "CORR. TEMP",
    "CORR. HUM",
    "MODO NOCHE",
    "C / F",
    "ESTADO HEAD",
    "WI-FI",
    "HORA / FECHA",
    "COLOR TEMA",
    "MQTT",
    "AUTO NOCHE",
    "REINICIAR",
    "RESET\nFÁBRICA",
    "CO2\nCALIBRACIÓN",
    "INFO",
    "PUNTOS\nINDICADORES",
    "ALERTA\nPARPADEO",
    "VOC\nREAPRENDER",
    "RETROILUM",
    "AJUSTES WI-FI",
    "Estado Wi-Fi:",
    "Para configurar Wi-Fi:\n- Pulsa ON / OFF\n- Conecta tu móvil o PC a \"ProjectAura-Setup\".\n- Abre http://192.168.4.1 o escanea el QR.\n- Elige tu red Wi-Fi y escribe la clave.\n",
    "SSID:",
    "IP:",
    "OLVIDAR\nWI-FI",
    "RECONECTAR",
    "INICIAR AP",
    "AJUSTES MQTT",
    "Estado MQTT:",
    "Para configurar MQTT:\n- Conecta Project Aura a WI-FI primero\n- Abre http://aura.local/mqtt o escanea el QR.",
    "IP dispositivo:",
    "IP broker:",
    "Topic:",
    "RECONECTAR",
    "FECHA Y HORA",
    "ZONA HORARIA",
    "AUTO SINCR. (NTP)",
    "AJUSTAR HORA",
    "Horas:",
    "Minutos:",
    "AJUSTAR FECHA",
    "Día:",
    "Mes:",
    "Año:",
    "HORA",
    "APLICAR",
    "RTC:",
    "WIFI:",
    "NTP:",
    "ESTADO: ",
    "TEMP",
    "HUMEDAD",
    "PRESIÓN",
    "CALENTANDO",
    "RESET VOC",
    "REINICIAR",
    "RESET",
    "CANCELAR",
    "¿Reiniciar calibración VOC?",
    "El aprendizaje VOC/NOx se reiniciará.\nLas lecturas pueden ser inestables unas horas.",
    "¿Reiniciar dispositivo?",
    "El dispositivo se reiniciará.\nLas lecturas se pausarán brevemente.",
    "¿Restablecer de fábrica?",
    "Esto borra Wi-Fi, offsets, temas,\nhorarios y estado VOC.\nNo se puede deshacer.",
    "TEMA:",
    "PERSONAL",
    "PRESETS",
    "EJEMPLO:",
    "Para tema personalizado:\n- Conecta Project Aura a WI-FI primero\n- Abre http://aura.local/theme \n  o escanea el QR.\n- Guarda pulsando Atrás",
    "MODO NOCHE AUTO",
    "Esta función activa \"Modo Noche\" por horario.\n- Ajusta hora inicio y fin.\n- Pon el interruptor en ON.\n- Modo Noche manual se desactiva\n  cuando Auto Noche está ON.",
    "HORA INICIO",
    "HORA FIN",
    "LUZ DE PANTALLA",
    "El dispositivo mide aire con pantalla apagada.\nSensores siguen activos. Toca para despertar.",
    "SUEÑO PROGRAMADO",
    "AHORRO ENERGÍA",
    "DORMIR A",
    "DESPERTAR A",
    "SIEMPRE",
    "30 SEG",
    "1 MIN",
    "5 MIN",
    "Calibración CO2 (Aire fresco)",
    "CALIBRAR\nCO2",
    "- ASC (Auto Self-Calibration): ON por defecto.\n- Mejor si CO2 baja cerca de exterior cada semana\n  (buena ventilación / sala vacía).\n- ASC ajusta lento (días, no al instante).\n- Con ASC ON normalmente no hace falta\n  calibración manual.",
    "- Alimenta con power bank.\n- Llévalo afuera a aire limpio.\n- Lejos de personas, ventanas, coches, humo, salidas.\n- Déjalo 10 min (mín. 5).\n- Pulsa Calibrar CO2 y no lo muevas.\n- Calibración manual solo para diagnóstico.\n- No más de cada 6 meses.\n- Usa referencia 420 ppm.\n- Malas condiciones empeoran lecturas.",
    "TOCA PARA SEGUIR",
    "DIAGNÓSTICO BOOT",
    "Sistema",
    "Sensores",
    "App:",
    "MAC:",
    "Reset:",
    "Heap:",
    "Almacenamiento:",
    "I2C:",
    "Touch:",
    "SEN66:",
    "SFA30:",
    "PCF8523:",
    "Errores detectados",
    "OK (config)",
    "OK (defecto)",
    "RECUPERADO",
    "DETECTADO",
    "FALLO",
    "INICIANDO",
    "NO ENCONTRADO",
    "PERDIDO",
    "AH muy bajo! Humidifica",
    "AH bajo - Usa humidificador",
    "AH alto - Riesgo de moho",
    "AH muy alto! Moho rápido",
    "Temperature affects comfort, productivity, and sleep quality. Thresholds based on ASHRAE Standard 55 (thermal comfort) and WHO housing recommendations. Optimal range helps maintain focus and prevents fatigue. Extremes cause discomfort, drowsiness, or difficulty concentrating. Prolonged exposure to poor conditions may affect health.",
    "Excellent: 20-25°C (68-77°F)\nIdeal range for comfort and productivity.",
    "Acceptable: 18-20°C or 25-26°C (64-68°F / 77-79°F)\nSlight discomfort possible.",
    "Uncomfortable: 16-18°C or 26-28°C (61-64°F / 79-82°F)\nNoticeable discomfort, lower productivity.",
    "Poor: <16°C or >28°C (<61°F / >82°F)\nSignificant discomfort, take action to adjust.",
    "VOC Index measures volatile organic compounds from paints, furniture, cleaning products, and cosmetics. Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased VOC concentration. Prolonged exposure may cause headaches, eye irritation, and fatigue. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=150\nNormal indoor air, no action needed",
    "Acceptable: 151-250\nSlight VOC elevation, consider ventilation",
    "Uncomfortable: 251-350\nNoticeable odors possible, ventilate recommended",
    "Poor: >350\nHeadaches and irritation likely, ventilate immediately",
    "NOx Index measures nitrogen oxides from combustion (traffic, gas stoves, heaters). Based on Sensirion SGP algorithm (1-500 scale). Index 100 represents baseline air. Higher values indicate increased NOx. Exposure can irritate lungs and worsen asthma. Ventilate when elevated. Blue indicator = sensor warming up.",
    "Excellent: <=50\nVery clean air",
    "Acceptable: 51-100\nSlight NOx elevation",
    "Uncomfortable: 101-200\nIrritation possible, ventilate recommended",
    "Poor: >200\nBreathing discomfort likely, ventilate immediately",
    "HCHO measures formaldehyde from furniture, pressed wood, fabrics, and some cleaners. Units in ppb. Higher levels can irritate eyes, nose, and throat. Prolonged exposure may affect breathing. Ventilate and reduce sources when elevated.",
    "Excellent: <30 ppb\nVery low formaldehyde",
    "Acceptable: 30-60 ppb\nLow level, keep ventilating",
    "Uncomfortable: 61-100 ppb\nIrritation possible, ventilate",
    "Poor: >100 ppb\nHealth risk, reduce sources and ventilate",
    "CO2 affects alertness, decision-making, and sleep quality. Outdoor air is about 420 ppm. Higher indoor levels indicate poor ventilation. Sustained exposure above 1000 ppm can reduce focus and cause drowsiness. Ventilate when elevated.",
    "Excellent: <800 ppm\nGood ventilation, optimal performance",
    "Acceptable: 800-1000 ppm\nSlightly elevated, consider airing",
    "Uncomfortable: 1001-1500 ppm\nDrowsiness possible, ventilate",
    "Poor: >1500 ppm\nHeadaches and low focus likely, ventilate now",
    "PM2.5 measures fine particles from combustion, smoke, and indoor sources. These particles penetrate deep into lungs and can affect heart health. High levels can worsen asthma and cause irritation. Use filtration and reduce sources when elevated.",
    "Excellent: <=12 ug/m3\nVery clean air",
    "Acceptable: 12-35 ug/m3\nSlight elevation, consider filtration",
    "Uncomfortable: 35-55 ug/m3\nRespiratory irritation possible",
    "Poor: >55 ug/m3\nHealth risk, reduce exposure",
    "PM10 measures coarse particles like dust, pollen, and road debris. High levels can irritate eyes, nose, and throat and worsen respiratory symptoms. Ventilate with clean air and reduce dust sources when elevated.",
    "Excellent: <=54 ug/m3\nClean air",
    "Acceptable: 54-154 ug/m3\nSome dust, sensitive groups may react",
    "Uncomfortable: 154-254 ug/m3\nIrritation likely, reduce exposure",
    "Poor: >254 ug/m3\nHigh pollution, stay indoors",
    "3h pressure trend shows short-term changes that can signal approaching weather. Rapid drops often precede storms; rapid rises indicate clearing. Use the delta below to judge how fast conditions are changing.",
    "Excellent: <1 hPa\nStable pressure",
    "Acceptable: 1-3 hPa\nMinor change",
    "Uncomfortable: 3-6 hPa\nNoticeable change",
    "Poor: >6 hPa\nRapid change, weather shift likely",
    "24h pressure trend shows daily change. Large swings suggest unstable weather; steady values mean stable conditions. Use the delta below to judge intensity.",
    "Excellent: <2 hPa\nStable conditions",
    "Acceptable: 2-6 hPa\nSmall change",
    "Uncomfortable: 6-10 hPa\nSignificant change",
    "Poor: >10 hPa\nMajor change, storms possible"
};

static_assert(sizeof(kStringsEn) / sizeof(kStringsEn[0]) ==
              static_cast<size_t>(TextId::Count),
              "UiStrings: EN table size mismatch");

Language g_language = Language::EN;

const char *const *tableFor(Language lang) {
    switch (lang) {
        case Language::DE: return kStringsDe;
        case Language::ES: return kStringsEs;
        case Language::FR: return kStringsFr;
        case Language::IT: return kStringsIt;
        case Language::PT: return kStringsPtBr;
        case Language::NL: return kStringsNl;
        case Language::ZH: return kStringsZh;
        case Language::EN:
        default:
            return kStringsEn;
    }
}

} // namespace

void setLanguage(Language lang) {
    g_language = lang;
}

Language language() {
    return g_language;
}

const char *text(TextId id) {
    const size_t index = static_cast<size_t>(id);
    const char *const *table = tableFor(g_language);
    const char *value = table ? table[index] : nullptr;
    if (!value || !*value) {
        value = kStringsEn[index];
    }
    return value ? value : "";
}

} // namespace UiStrings



